//! The VMI-Scope application: state, request/response plumbing, and UI.
//!
//! The UI never blocks. Every WMI operation is dispatched to the background
//! [`WmiWorker`] with a monotonically increasing request id; replies are drained
//! once per frame in [`VmiScopeApp::handle_responses`]. `pending` maps in-flight
//! ids to what they were for, so an error reply can clear the right spinner.

use std::collections::{HashMap, HashSet};
use std::time::Duration;

use eframe::egui;
use egui::Color32;
use egui_extras::{Column, TableBuilder};

use vmiscope_core::{
    Connection, Protocol, QueryResult, Request, Response, Risk, Subscription, SubscriptionReport,
    WmiWorker,
};

const ROOT_NAMESPACE: &str = "root";
const DEFAULT_NAMESPACE: &str = "root\\CIMV2";
const DEFAULT_QUERY: &str = "SELECT * FROM Win32_OperatingSystem";

/// How often the Network tab re-snapshots the connection table.
const NET_REFRESH_SECS: f64 = 1.5;
/// How long a closed connection lingers (fading) before it disappears.
const NET_FADE_SECS: f64 = 6.0;

/// The top-level tools.
#[derive(PartialEq, Eq, Clone, Copy)]
enum Tab {
    Explorer,
    Network,
    Persistence,
}

/// A connection tracked across snapshots so it can fade out after it closes.
struct TrackedConn {
    conn: Connection,
    last_seen: f64,
    /// Present in the most recent snapshot?
    alive: bool,
}

/// What an in-flight request id was asking for — used to clear the correct
/// loading state when a reply (or error) arrives.
enum PendingKind {
    Namespaces(String),
    Classes,
    Query,
    Network,
    Events,
}

/// Colour for a subscription risk level.
fn risk_color(risk: Risk) -> Color32 {
    match risk {
        Risk::High => Color32::from_rgb(240, 100, 100),
        Risk::Medium => Color32::from_rgb(225, 185, 90),
        Risk::Low => Color32::from_rgb(150, 165, 150),
    }
}

/// Target language for the script generator.
#[derive(PartialEq, Eq, Clone, Copy)]
enum ScriptLang {
    PowerShell,
    VbScript,
}

/// Produce a runnable script equivalent to the current namespace + WQL query.
fn generate_script(lang: ScriptLang, namespace: &str, wql: &str) -> String {
    let ns = namespace.trim();
    let q = wql.trim();
    match lang {
        ScriptLang::PowerShell => format!(
            "# Generated by VMI-Scope\n\
             $namespace = '{ns}'\n\
             $query     = @'\n\
             {q}\n\
             '@\n\n\
             Get-CimInstance -Namespace $namespace -Query $query | Format-List *\n"
        ),
        ScriptLang::VbScript => {
            let q = q.replace('"', "\"\""); // VBScript escapes quotes by doubling
            format!(
                "' Generated by VMI-Scope\n\
                 strNamespace = \"{ns}\"\n\
                 strQuery     = \"{q}\"\n\n\
                 Set objWMI   = GetObject(\"winmgmts:\\\\.\\\" & strNamespace)\n\
                 Set colItems = objWMI.ExecQuery(strQuery)\n\
                 For Each objItem In colItems\n\
                 \x20   WScript.Echo \"----------------------------------------\"\n\
                 \x20   For Each objProp In objItem.Properties_\n\
                 \x20       WScript.Echo objProp.Name & \" = \" & objProp.Value\n\
                 \x20   Next\n\
                 Next\n"
            )
        }
    }
}

/// Colour a connection by protocol/state (before fade alpha is applied).
fn state_color(state: &str, proto: Protocol) -> Color32 {
    if proto == Protocol::Udp {
        return Color32::from_rgb(120, 170, 220);
    }
    match state {
        "Established" => Color32::from_rgb(120, 210, 140), // green — active
        "Listen" | "Bound" => Color32::from_rgb(120, 170, 220), // blue — server socket
        "SynSent" | "SynReceived" | "FinWait1" | "FinWait2" | "CloseWait" | "Closing"
        | "LastAck" | "TimeWait" => Color32::from_rgb(220, 190, 110), // amber — transitional
        "Closed" | "DeleteTCB" => Color32::from_rgb(165, 165, 165), // gray
        _ => Color32::from_rgb(205, 205, 205),
    }
}

/// The display string for a network table column (kept in sync with the header
/// order so sorting matches what's shown).
fn net_col_value(c: &Connection, col: usize) -> String {
    match col {
        0 => c.proto.as_str().to_string(),
        1 => c.state.clone(),
        2 => c.local_addr.clone(),
        3 => c.local_port.to_string(),
        4 => c.remote_addr.clone(),
        5 => {
            if c.proto == Protocol::Udp {
                String::new()
            } else {
                c.remote_port.to_string()
            }
        }
        6 => c.pid.to_string(),
        7 => c.process.clone(),
        _ => String::new(),
    }
}

/// The display/sort string for a persistence table column. Column 0 (risk) maps
/// to a numeric severity so sorting orders by danger, not alphabetically.
fn sub_col_value(s: &Subscription, col: usize) -> String {
    match col {
        0 => match s.risk {
            Risk::High => "3",
            Risk::Medium => "2",
            Risk::Low => "1",
        }
        .to_string(),
        1 => s.consumer_type.clone(),
        2 => s.consumer_name.clone(),
        3 => s.filter_name.clone(),
        4 => {
            if s.action.is_empty() {
                s.filter_query.clone()
            } else {
                s.action.clone()
            }
        }
        5 => s.reasons.join("; "),
        _ => String::new(),
    }
}

/// Compare two cells numerically when both parse as numbers, else case-insensitively.
fn smart_cmp(a: &str, b: &str) -> std::cmp::Ordering {
    match (a.parse::<f64>(), b.parse::<f64>()) {
        (Ok(x), Ok(y)) => x.partial_cmp(&y).unwrap_or(std::cmp::Ordering::Equal),
        _ => a.to_lowercase().cmp(&b.to_lowercase()),
    }
}

/// Cycle a column's sort: unsorted → ascending → descending → unsorted.
fn toggle_sort(current: &mut Option<(usize, bool)>, col: usize) {
    *current = match *current {
        Some((c, true)) if c == col => Some((col, false)),
        Some((c, false)) if c == col => None,
        _ => Some((col, true)),
    };
}

/// A sortable header cell: shows the title plus a ▲/▼ marker when it's the
/// active sort column. Returns true if the user clicked it.
fn sortable_header(
    ui: &mut egui::Ui,
    title: &str,
    col: usize,
    sort: Option<(usize, bool)>,
) -> bool {
    let marker = match sort {
        Some((c, true)) if c == col => " \u{25b2}",
        Some((c, false)) if c == col => " \u{25bc}",
        _ => "",
    };
    ui.add(egui::Button::new(egui::RichText::new(format!("{title}{marker}")).strong()).frame(false))
        .clicked()
}

pub struct VmiScopeApp {
    worker: WmiWorker,
    next_id: u64,
    pending: HashMap<u64, PendingKind>,
    active_tab: Tab,

    // --- network tab ---
    net_conns: HashMap<String, TrackedConn>,
    net_last_refresh: f64,
    net_inflight: bool,
    net_filter: String,
    net_paused: bool,
    /// (column index, ascending). `None` = default (grouped by process).
    net_sort: Option<(usize, bool)>,

    // --- persistence tab ---
    events_report: Option<SubscriptionReport>,
    events_loading: bool,
    events_sort: Option<(usize, bool)>,

    // --- namespace tree ---
    /// namespace path -> its loaded child paths (absent = not loaded yet).
    ns_children: HashMap<String, Vec<String>>,
    ns_expanded: HashSet<String>,
    ns_loading: HashSet<String>,
    active_ns: String,

    // --- class list (for the active namespace) ---
    classes: Vec<String>,
    classes_ns: String,
    classes_loading: bool,
    class_filter: String,
    selected_class: Option<String>,

    // --- query + results ---
    query_text: String,
    script_lang: ScriptLang,
    latest_query_id: u64,
    query_loading: bool,
    result: Option<QueryResult>,
    result_wql: String,
    selected_row: Option<usize>,
    /// (column index, ascending). `None` = original result order.
    result_sort: Option<(usize, bool)>,

    // --- status ---
    error: Option<String>,
}

impl VmiScopeApp {
    pub fn new(cc: &eframe::CreationContext<'_>) -> Self {
        cc.egui_ctx.set_visuals(egui::Visuals::dark());

        let mut app = Self {
            worker: WmiWorker::spawn(),
            next_id: 0,
            pending: HashMap::new(),
            active_tab: Tab::Explorer,
            net_conns: HashMap::new(),
            net_last_refresh: 0.0,
            net_inflight: false,
            net_filter: String::new(),
            net_paused: false,
            net_sort: None,
            events_report: None,
            events_loading: false,
            events_sort: None,
            ns_children: HashMap::new(),
            ns_expanded: HashSet::new(),
            ns_loading: HashSet::new(),
            active_ns: DEFAULT_NAMESPACE.to_string(),
            classes: Vec::new(),
            classes_ns: String::new(),
            classes_loading: false,
            class_filter: String::new(),
            selected_class: None,
            query_text: DEFAULT_QUERY.to_string(),
            script_lang: ScriptLang::PowerShell,
            latest_query_id: 0,
            query_loading: false,
            result: None,
            result_wql: String::new(),
            selected_row: None,
            result_sort: None,
            error: None,
        };

        // Load the root's children, expand it, focus CIMV2, and run a query so
        // the window has real content the moment it opens.
        app.ns_expanded.insert(ROOT_NAMESPACE.to_string());
        app.request_namespaces(ROOT_NAMESPACE.to_string());
        app.request_classes(DEFAULT_NAMESPACE.to_string());
        app.run_query();
        app
    }

    // ------------------------------------------------------------------
    // request helpers
    // ------------------------------------------------------------------

    fn alloc_id(&mut self) -> u64 {
        self.next_id += 1;
        self.next_id
    }

    fn request_namespaces(&mut self, namespace: String) {
        if self.ns_loading.contains(&namespace) || self.ns_children.contains_key(&namespace) {
            return;
        }
        let id = self.alloc_id();
        self.ns_loading.insert(namespace.clone());
        self.pending
            .insert(id, PendingKind::Namespaces(namespace.clone()));
        self.worker
            .send(Request::ListChildNamespaces { id, namespace });
    }

    fn request_classes(&mut self, namespace: String) {
        let id = self.alloc_id();
        self.classes_loading = true;
        self.classes_ns = namespace.clone();
        self.classes.clear();
        self.pending.insert(id, PendingKind::Classes);
        self.worker.send(Request::ListClasses { id, namespace });
    }

    fn request_network(&mut self, now: f64) {
        let id = self.alloc_id();
        self.net_inflight = true;
        self.net_last_refresh = now;
        self.pending.insert(id, PendingKind::Network);
        self.worker.send(Request::NetworkSnapshot { id });
    }

    fn request_events(&mut self) {
        let id = self.alloc_id();
        self.events_loading = true;
        self.pending.insert(id, PendingKind::Events);
        self.worker.send(Request::ListEventSubscriptions { id });
    }

    fn run_query(&mut self) {
        let wql = self.query_text.trim().to_string();
        if wql.is_empty() {
            return;
        }
        let id = self.alloc_id();
        self.latest_query_id = id;
        self.query_loading = true;
        self.error = None;
        self.pending.insert(id, PendingKind::Query);
        self.worker.send(Request::Query {
            id,
            namespace: self.active_ns.clone(),
            wql,
        });
    }

    // ------------------------------------------------------------------
    // selection actions
    // ------------------------------------------------------------------

    fn select_namespace(&mut self, namespace: String) {
        if self.active_ns == namespace {
            return;
        }
        self.active_ns = namespace.clone();
        self.selected_class = None;
        self.request_classes(namespace);
    }

    fn toggle_namespace(&mut self, path: &str) {
        if self.ns_expanded.contains(path) {
            self.ns_expanded.remove(path);
        } else {
            self.ns_expanded.insert(path.to_string());
            self.request_namespaces(path.to_string());
        }
    }

    fn select_class(&mut self, class: String) {
        self.query_text = format!("SELECT * FROM {class}");
        self.selected_class = Some(class);
        self.run_query();
    }

    // ------------------------------------------------------------------
    // response handling
    // ------------------------------------------------------------------

    fn handle_responses(&mut self, now: f64) {
        for resp in self.worker.poll() {
            match resp {
                Response::ChildNamespaces {
                    id,
                    namespace,
                    children,
                } => {
                    self.pending.remove(&id);
                    self.ns_loading.remove(&namespace);
                    self.ns_children.insert(namespace, children);
                }
                Response::Classes {
                    id,
                    namespace,
                    classes,
                } => {
                    self.pending.remove(&id);
                    // Only apply if it still matches the namespace we care about.
                    if namespace == self.classes_ns {
                        self.classes = classes;
                        self.classes_loading = false;
                    }
                }
                Response::QueryResult {
                    id, wql, result, ..
                } => {
                    self.pending.remove(&id);
                    // Ignore stale results from superseded queries.
                    if id == self.latest_query_id {
                        self.result = Some(result);
                        self.result_wql = wql;
                        self.selected_row = None;
                        self.result_sort = None;
                        self.query_loading = false;
                        self.error = None;
                    }
                }
                Response::Network { id, snapshot } => {
                    self.pending.remove(&id);
                    self.net_inflight = false;
                    // Mark everything stale, then revive whatever is present now.
                    for tc in self.net_conns.values_mut() {
                        tc.alive = false;
                    }
                    for conn in snapshot.connections {
                        let key = conn.key();
                        match self.net_conns.get_mut(&key) {
                            Some(tc) => {
                                tc.conn = conn;
                                tc.last_seen = now;
                                tc.alive = true;
                            }
                            None => {
                                self.net_conns.insert(
                                    key,
                                    TrackedConn {
                                        conn,
                                        last_seen: now,
                                        alive: true,
                                    },
                                );
                            }
                        }
                    }
                    // Drop connections that have fully faded out.
                    self.net_conns
                        .retain(|_, tc| tc.alive || (now - tc.last_seen) < NET_FADE_SECS);
                }
                Response::EventSubscriptions { id, report } => {
                    self.pending.remove(&id);
                    self.events_loading = false;
                    self.events_report = Some(report);
                }
                Response::Error {
                    id,
                    context,
                    message,
                } => {
                    let kind = self.pending.remove(&id);
                    match kind {
                        Some(PendingKind::Namespaces(ns)) => {
                            self.ns_loading.remove(&ns);
                        }
                        Some(PendingKind::Classes) => {
                            self.classes_loading = false;
                        }
                        Some(PendingKind::Query) => {
                            if id == self.latest_query_id {
                                self.query_loading = false;
                            }
                        }
                        Some(PendingKind::Network) => {
                            self.net_inflight = false;
                        }
                        Some(PendingKind::Events) => {
                            self.events_loading = false;
                        }
                        None => {}
                    }
                    self.error = Some(format!("{context}\n{message}"));
                }
            }
        }
    }

    // ------------------------------------------------------------------
    // UI: namespace tree
    // ------------------------------------------------------------------

    fn ui_namespace_tree(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            ui.strong("Namespaces");
            if self.ns_loading.contains(ROOT_NAMESPACE) {
                ui.spinner();
            }
        });
        ui.separator();
        egui::ScrollArea::vertical()
            .id_salt("ns-tree")
            .max_height(ui.available_height() * 0.45)
            .auto_shrink([false, false])
            .show(ui, |ui| {
                self.ui_namespace_node(ui, ROOT_NAMESPACE.to_string(), 0);
            });
    }

    fn ui_namespace_node(&mut self, ui: &mut egui::Ui, path: String, depth: usize) {
        let expanded = self.ns_expanded.contains(&path);
        let leaf = path.rsplit('\\').next().unwrap_or(&path).to_string();

        ui.horizontal(|ui| {
            ui.add_space(depth as f32 * 14.0);
            let arrow = if expanded { "\u{25be}" } else { "\u{25b8}" }; // ▾ / ▸
            if ui
                .add(egui::Button::new(arrow).frame(false))
                .on_hover_text("Expand / collapse")
                .clicked()
            {
                self.toggle_namespace(&path);
            }
            if ui
                .selectable_label(self.active_ns.eq_ignore_ascii_case(&path), &leaf)
                .clicked()
            {
                self.select_namespace(path.clone());
            }
        });

        if expanded {
            match self.ns_children.get(&path).cloned() {
                Some(children) => {
                    for child in children {
                        self.ui_namespace_node(ui, child, depth + 1);
                    }
                }
                None => {
                    ui.horizontal(|ui| {
                        ui.add_space((depth as f32 + 1.0) * 14.0);
                        ui.spinner();
                        ui.weak("loading\u{2026}");
                    });
                }
            }
        }
    }

    // ------------------------------------------------------------------
    // UI: class list
    // ------------------------------------------------------------------

    fn ui_class_list(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            ui.strong("Classes");
            if self.classes_loading {
                ui.spinner();
            }
            ui.weak(format!("({})", self.classes.len()));
        });
        ui.horizontal(|ui| {
            ui.label("\u{1f50d}");
            ui.add(
                egui::TextEdit::singleline(&mut self.class_filter)
                    .hint_text("filter classes")
                    .desired_width(f32::INFINITY),
            );
        });
        ui.separator();

        let mut clicked: Option<String> = None;
        {
            let filter = self.class_filter.to_lowercase();
            let filtered: Vec<&String> = self
                .classes
                .iter()
                .filter(|c| filter.is_empty() || c.to_lowercase().contains(&filter))
                .collect();
            let row_h = ui.text_style_height(&egui::TextStyle::Body) + 4.0;
            egui::ScrollArea::vertical()
                .id_salt("class-list")
                .auto_shrink([false, false])
                .show_rows(ui, row_h, filtered.len(), |ui, range| {
                    for i in range {
                        let class = filtered[i];
                        let selected = self.selected_class.as_deref() == Some(class.as_str());
                        if ui.selectable_label(selected, class).clicked() {
                            clicked = Some(class.clone());
                        }
                    }
                });
        }
        if let Some(class) = clicked {
            self.select_class(class);
        }
    }

    // ------------------------------------------------------------------
    // UI: query editor + results table
    // ------------------------------------------------------------------

    fn ui_central(&mut self, ui: &mut egui::Ui) {
        // Query bar.
        ui.horizontal(|ui| {
            ui.strong("WQL");
            ui.weak(&self.active_ns);
            if self.query_loading {
                ui.spinner();
            }
        });
        let run_shortcut = ui.input(|i| i.modifiers.command && i.key_pressed(egui::Key::Enter));
        ui.add(
            egui::TextEdit::multiline(&mut self.query_text)
                .desired_rows(2)
                .desired_width(f32::INFINITY)
                .code_editor()
                .hint_text("SELECT * FROM Win32_Process"),
        );
        ui.horizontal(|ui| {
            if ui.button("\u{25b6} Run  (Ctrl+Enter)").clicked() || run_shortcut {
                self.run_query();
            }
            if let Some(result) = &self.result {
                ui.weak(format!(
                    "{} rows \u{00d7} {} cols",
                    result.rows.len(),
                    result.columns.len()
                ));
            }
        });

        self.ui_script_gen(ui);
        ui.separator();

        // Results table (virtualized, sortable by clicking a header).
        let selected_row = self.selected_row;
        let sort = self.result_sort;
        let mut newly_clicked: Option<usize> = None;
        let mut header_clicked: Option<usize> = None;
        if let Some(result) = self.result.as_ref() {
            if result.columns.is_empty() {
                ui.weak("Query returned no columns.");
            } else {
                // Row display order for the active sort column.
                let mut order: Vec<usize> = (0..result.rows.len()).collect();
                if let Some((ci, asc)) = sort {
                    order.sort_by(|&a, &b| {
                        let av = result.rows[a].get(ci).map(String::as_str).unwrap_or("");
                        let bv = result.rows[b].get(ci).map(String::as_str).unwrap_or("");
                        let o = smart_cmp(av, bv);
                        if asc {
                            o
                        } else {
                            o.reverse()
                        }
                    });
                }

                let row_h = ui.text_style_height(&egui::TextStyle::Body) + 6.0;
                let ncols = result.columns.len();
                let mut table = TableBuilder::new(ui)
                    .id_salt("results-table")
                    .striped(true)
                    .resizable(true)
                    .sense(egui::Sense::click())
                    .cell_layout(egui::Layout::left_to_right(egui::Align::Center))
                    .min_scrolled_height(0.0);
                for _ in 0..ncols {
                    table = table.column(
                        Column::initial(150.0)
                            .at_least(48.0)
                            .clip(true)
                            .resizable(true),
                    );
                }
                table
                    .header(22.0, |mut header| {
                        for (ci, col) in result.columns.iter().enumerate() {
                            header.col(|ui| {
                                if sortable_header(ui, col, ci, sort) {
                                    header_clicked = Some(ci);
                                }
                            });
                        }
                    })
                    .body(|body| {
                        body.rows(row_h, order.len(), |mut row| {
                            let actual = order[row.index()];
                            row.set_selected(selected_row == Some(actual));
                            for cell in &result.rows[actual] {
                                row.col(|ui| {
                                    ui.label(cell);
                                });
                            }
                            if row.response().clicked() {
                                newly_clicked = Some(actual);
                            }
                        });
                    });
            }
        } else {
            ui.weak("Run a query to see results.");
        }
        if let Some(ci) = header_clicked {
            toggle_sort(&mut self.result_sort, ci);
        }
        if let Some(ri) = newly_clicked {
            self.selected_row = Some(ri);
        }
    }

    /// Collapsible PowerShell / VBScript generator for the current query.
    fn ui_script_gen(&mut self, ui: &mut egui::Ui) {
        ui.collapsing("\u{1f4dc} Generate script (PowerShell / VBScript)", |ui| {
            ui.horizontal(|ui| {
                ui.selectable_value(&mut self.script_lang, ScriptLang::PowerShell, "PowerShell");
                ui.selectable_value(&mut self.script_lang, ScriptLang::VbScript, "VBScript");
            });
            let script = generate_script(self.script_lang, &self.active_ns, &self.query_text);
            ui.horizontal(|ui| {
                if ui.button("\u{1f4cb} Copy").clicked() {
                    ui.ctx().copy_text(script.clone());
                }
                ui.weak("PowerShell: paste & run \u{00b7} VBScript: cscript file.vbs");
            });
            egui::ScrollArea::vertical()
                .id_salt("script-box")
                .max_height(150.0)
                .auto_shrink([false, false])
                .show(ui, |ui| {
                    ui.add(
                        egui::Label::new(egui::RichText::new(script.as_str()).monospace())
                            .selectable(true),
                    );
                });
        });
    }

    // ------------------------------------------------------------------
    // UI: selected-row detail
    // ------------------------------------------------------------------

    fn ui_detail(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            ui.strong("Row detail");
            if ui.small_button("\u{2715}").on_hover_text("Close").clicked() {
                self.selected_row = None;
            }
        });
        ui.separator();
        let (Some(result), Some(ri)) = (self.result.as_ref(), self.selected_row) else {
            return;
        };
        let Some(row) = result.rows.get(ri) else {
            return;
        };
        egui::ScrollArea::vertical()
            .auto_shrink([false, false])
            .show(ui, |ui| {
                egui::Grid::new("detail-grid")
                    .num_columns(2)
                    .striped(true)
                    .spacing([12.0, 4.0])
                    .show(ui, |ui| {
                        for (col, val) in result.columns.iter().zip(row.iter()) {
                            ui.strong(col);
                            if val.is_empty() {
                                ui.weak("\u{2014}"); // em dash for empty
                            } else {
                                ui.label(val);
                            }
                            ui.end_row();
                        }
                    });
            });
    }

    // ------------------------------------------------------------------
    // UI: live network monitor
    // ------------------------------------------------------------------

    fn ui_network(&mut self, ui: &mut egui::Ui, now: f64) {
        // Controls.
        ui.horizontal(|ui| {
            ui.strong("Live connections");
            if self.net_inflight {
                ui.spinner();
            }
            let pause = if self.net_paused {
                "\u{25b6} Resume"
            } else {
                "\u{23f8} Pause"
            };
            if ui.button(pause).clicked() {
                self.net_paused = !self.net_paused;
            }
            if ui.button("\u{21bb} Refresh").clicked() {
                self.request_network(now);
            }
            ui.separator();
            ui.label("\u{1f50d}");
            ui.add(
                egui::TextEdit::singleline(&mut self.net_filter)
                    .hint_text("filter process / ip / port / state")
                    .desired_width(240.0),
            );
        });

        let active = self.net_conns.values().filter(|t| t.alive).count();
        let fading = self.net_conns.len().saturating_sub(active);
        ui.horizontal(|ui| {
            ui.colored_label(
                Color32::from_rgb(120, 210, 140),
                format!("\u{25cf} {active} active"),
            );
            ui.weak(format!("\u{25cb} {fading} closing"));
            ui.weak("\u{2014}  auto-refresh 1.5s, closed connections fade out over ~6s");
        });
        ui.separator();

        // Filter + sort (stable order so fading rows stay put while they dim).
        let filter = self.net_filter.to_lowercase();
        let mut rows: Vec<&TrackedConn> = self
            .net_conns
            .values()
            .filter(|t| {
                if filter.is_empty() {
                    return true;
                }
                let c = &t.conn;
                c.process.to_lowercase().contains(&filter)
                    || c.local_addr.contains(&filter)
                    || c.remote_addr.contains(&filter)
                    || c.local_port.to_string().contains(&filter)
                    || c.remote_port.to_string().contains(&filter)
                    || c.state.to_lowercase().contains(&filter)
            })
            .collect();
        let sort = self.net_sort;
        match sort {
            Some((ci, asc)) => rows.sort_by(|a, b| {
                let o = smart_cmp(&net_col_value(&a.conn, ci), &net_col_value(&b.conn, ci));
                if asc {
                    o
                } else {
                    o.reverse()
                }
            }),
            // Default: group by process, then local port (stable while fading).
            None => rows.sort_by(|a, b| {
                a.conn
                    .process
                    .to_lowercase()
                    .cmp(&b.conn.process.to_lowercase())
                    .then(a.conn.proto.as_str().cmp(b.conn.proto.as_str()))
                    .then(a.conn.local_port.cmp(&b.conn.local_port))
                    .then(a.conn.remote_addr.cmp(&b.conn.remote_addr))
                    .then(a.conn.remote_port.cmp(&b.conn.remote_port))
            }),
        }

        let headers = [
            "Proto",
            "State",
            "Local address",
            "L.Port",
            "Remote address",
            "R.Port",
            "PID",
            "Process",
        ];
        let widths = [52.0, 96.0, 190.0, 60.0, 190.0, 60.0, 64.0, 180.0];
        let row_h = ui.text_style_height(&egui::TextStyle::Body) + 6.0;

        let mut header_clicked: Option<usize> = None;
        let mut table = TableBuilder::new(ui)
            .id_salt("net-table")
            .striped(true)
            .resizable(true)
            .cell_layout(egui::Layout::left_to_right(egui::Align::Center))
            .min_scrolled_height(0.0);
        for w in widths {
            table = table.column(Column::initial(w).at_least(40.0).clip(true).resizable(true));
        }
        table
            .header(22.0, |mut header| {
                for (ci, h) in headers.iter().enumerate() {
                    header.col(|ui| {
                        if sortable_header(ui, h, ci, sort) {
                            header_clicked = Some(ci);
                        }
                    });
                }
            })
            .body(|body| {
                body.rows(row_h, rows.len(), |mut row| {
                    let t = rows[row.index()];
                    let c = &t.conn;
                    // Alpha: full while alive, fading toward transparent after close.
                    let alpha = if t.alive {
                        1.0
                    } else {
                        (1.0 - (now - t.last_seen) / NET_FADE_SECS).clamp(0.06, 1.0) as f32
                    };
                    let color = state_color(&c.state, c.proto).gamma_multiply(alpha);

                    let is_udp = c.proto == Protocol::Udp;
                    let cells = [
                        c.proto.as_str().to_string(),
                        if c.state.is_empty() {
                            "\u{2014}".into()
                        } else {
                            c.state.clone()
                        },
                        c.local_addr.clone(),
                        c.local_port.to_string(),
                        if c.remote_addr.is_empty() {
                            "*".into()
                        } else {
                            c.remote_addr.clone()
                        },
                        if is_udp {
                            "*".into()
                        } else {
                            c.remote_port.to_string()
                        },
                        c.pid.to_string(),
                        c.process.clone(),
                    ];
                    for cell in cells {
                        row.col(|ui| {
                            ui.label(egui::RichText::new(cell).color(color));
                        });
                    }
                });
            });

        if let Some(ci) = header_clicked {
            toggle_sort(&mut self.net_sort, ci);
        }
    }

    // ------------------------------------------------------------------
    // UI: persistence (WMI event-subscription hunter)
    // ------------------------------------------------------------------

    fn ui_persistence(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            ui.strong("WMI event subscriptions");
            if self.events_loading {
                ui.spinner();
            }
            if ui.button("\u{21bb} Refresh").clicked() {
                self.request_events();
            }
            ui.weak("root\\subscription — permanent subscriptions (persistence)");
        });

        if let Some(report) = self.events_report.as_ref() {
            ui.horizontal(|ui| {
                ui.colored_label(
                    risk_color(Risk::High),
                    format!("\u{25cf} {} high", report.count(Risk::High)),
                );
                ui.colored_label(
                    risk_color(Risk::Medium),
                    format!("\u{25cf} {} medium", report.count(Risk::Medium)),
                );
                ui.colored_label(
                    risk_color(Risk::Low),
                    format!("\u{25cf} {} low", report.count(Risk::Low)),
                );
            });
        }
        ui.separator();

        let sort = self.events_sort;
        let mut header_clicked: Option<usize> = None;

        if let Some(report) = self.events_report.as_ref() {
            if report.subscriptions.is_empty() {
                ui.weak("No permanent event subscriptions found.");
            } else {
                let mut order: Vec<usize> = (0..report.subscriptions.len()).collect();
                if let Some((ci, asc)) = sort {
                    order.sort_by(|&a, &b| {
                        let o = smart_cmp(
                            &sub_col_value(&report.subscriptions[a], ci),
                            &sub_col_value(&report.subscriptions[b], ci),
                        );
                        if asc {
                            o
                        } else {
                            o.reverse()
                        }
                    });
                }

                let headers = [
                    "Risk",
                    "Consumer type",
                    "Consumer",
                    "Filter",
                    "Action / query",
                    "Why",
                ];
                let widths = [64.0, 168.0, 150.0, 150.0, 260.0, 220.0];
                let row_h = ui.text_style_height(&egui::TextStyle::Body) + 6.0;

                let mut table = TableBuilder::new(ui)
                    .id_salt("events-table")
                    .striped(true)
                    .resizable(true)
                    .cell_layout(egui::Layout::left_to_right(egui::Align::Center))
                    .min_scrolled_height(0.0);
                for w in widths {
                    table =
                        table.column(Column::initial(w).at_least(48.0).clip(true).resizable(true));
                }
                table
                    .header(22.0, |mut header| {
                        for (ci, h) in headers.iter().enumerate() {
                            header.col(|ui| {
                                if sortable_header(ui, h, ci, sort) {
                                    header_clicked = Some(ci);
                                }
                            });
                        }
                    })
                    .body(|body| {
                        body.rows(row_h, order.len(), |mut row| {
                            let s = &report.subscriptions[order[row.index()]];
                            let color = risk_color(s.risk);
                            row.col(|ui| {
                                ui.label(
                                    egui::RichText::new(s.risk.as_str()).color(color).strong(),
                                );
                            });
                            row.col(|ui| {
                                ui.label(s.consumer_type.as_str());
                            });
                            row.col(|ui| {
                                ui.label(s.consumer_name.as_str());
                            });
                            row.col(|ui| {
                                ui.label(s.filter_name.as_str());
                            });
                            row.col(|ui| {
                                let text = if s.action.is_empty() {
                                    s.filter_query.as_str()
                                } else {
                                    s.action.as_str()
                                };
                                ui.label(text).on_hover_text(format!(
                                    "filter query:\n{}\n\naction:\n{}",
                                    s.filter_query, s.action
                                ));
                            });
                            row.col(|ui| {
                                let why = s.reasons.join("; ");
                                ui.label(egui::RichText::new(why.as_str()).color(color))
                                    .on_hover_text(why);
                            });
                        });
                    });
            }
        } else if !self.events_loading {
            ui.weak("Click Refresh to scan for WMI persistence.");
        }

        if let Some(ci) = header_clicked {
            toggle_sort(&mut self.events_sort, ci);
        }
    }

    // ------------------------------------------------------------------
    // UI: status bar
    // ------------------------------------------------------------------

    fn ui_status(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            if let Some(err) = &self.error {
                ui.colored_label(egui::Color32::from_rgb(240, 90, 90), "\u{26a0} error");
                ui.weak("\u{2014}");
                ui.label(err.replace('\n', "  \u{2014}  "));
            } else {
                ui.weak(format!("Namespace: {}", self.active_ns));
                if !self.result_wql.is_empty() {
                    ui.weak("\u{2014}");
                    ui.weak(&self.result_wql);
                }
            }
        });
    }
}

impl eframe::App for VmiScopeApp {
    // eframe 0.35 hands the app the root `Ui` directly and attaches panels to it
    // via `show(ui, ..)` (instead of the older `update(ctx, ..)` model).
    fn ui(&mut self, ui: &mut egui::Ui, _frame: &mut eframe::Frame) {
        let now = ui.input(|i| i.time);
        self.handle_responses(now);

        // Drive the live network refresh from the frame clock.
        if self.active_tab == Tab::Network
            && !self.net_paused
            && !self.net_inflight
            && (now - self.net_last_refresh) >= NET_REFRESH_SECS
        {
            self.request_network(now);
        }

        // Load the persistence scan the first time its tab is opened.
        if self.active_tab == Tab::Persistence
            && self.events_report.is_none()
            && !self.events_loading
        {
            self.request_events();
        }

        egui::Panel::top("top").show(ui, |ui| {
            ui.add_space(4.0);
            ui.horizontal(|ui| {
                ui.heading("VMI-Scope");
                ui.separator();
                ui.selectable_value(&mut self.active_tab, Tab::Explorer, "\u{1f5c2} Explorer");
                ui.selectable_value(&mut self.active_tab, Tab::Network, "\u{1f5a7} Network");
                ui.selectable_value(
                    &mut self.active_tab,
                    Tab::Persistence,
                    "\u{1f6e1} Persistence",
                );
            });
            ui.add_space(4.0);
        });

        egui::Panel::bottom("status").show(ui, |ui| {
            self.ui_status(ui);
        });

        match self.active_tab {
            Tab::Explorer => {
                egui::Panel::left("browser")
                    .resizable(true)
                    .default_size(300.0)
                    .size_range(egui::Rangef::new(200.0, 520.0))
                    .show(ui, |ui| {
                        self.ui_namespace_tree(ui);
                        ui.add_space(8.0);
                        self.ui_class_list(ui);
                    });

                if self.selected_row.is_some() {
                    egui::Panel::right("detail")
                        .resizable(true)
                        .default_size(340.0)
                        .size_range(egui::Rangef::new(220.0, 560.0))
                        .show(ui, |ui| {
                            self.ui_detail(ui);
                        });
                }

                egui::CentralPanel::default().show(ui, |ui| {
                    self.ui_central(ui);
                });
            }
            Tab::Network => {
                egui::CentralPanel::default().show(ui, |ui| {
                    self.ui_network(ui, now);
                });
            }
            Tab::Persistence => {
                egui::CentralPanel::default().show(ui, |ui| {
                    self.ui_persistence(ui);
                });
            }
        }

        // Repaint while work is in flight, and continuously on the live tab.
        if !self.pending.is_empty() {
            ui.ctx().request_repaint_after(Duration::from_millis(30));
        }
        if self.active_tab == Tab::Network && !self.net_paused {
            ui.ctx().request_repaint_after(Duration::from_millis(200));
        }
    }
}
