//! The VMI-Scope application: state, request/response plumbing, and UI.
//!
//! The UI never blocks. Every WMI operation is dispatched to the background
//! [`WmiWorker`] with a monotonically increasing request id; replies are drained
//! once per frame in [`VmiScopeApp::handle_responses`]. `pending` maps in-flight
//! ids to what they were for, so an error reply can clear the right spinner.

use std::collections::{HashMap, HashSet};
use std::time::Duration;

use eframe::egui;
use egui::Color32;
use egui_extras::{Column, TableBuilder};

use vmiscope_core::{
    param_kind, ClassSchema, Connection, MethodArg, MethodOutcome, MethodTarget, ParamKind,
    Protocol, ProviderInfo, QueryResult, Request, Response, Risk, SearchHit, SearchIndex,
    Subscription, SubscriptionReport, WmiWorker,
};

const ROOT_NAMESPACE: &str = "root";
const DEFAULT_NAMESPACE: &str = "root\\CIMV2";
const DEFAULT_QUERY: &str = "SELECT * FROM Win32_OperatingSystem";

/// How often the Network tab re-snapshots the connection table.
const NET_REFRESH_SECS: f64 = 1.5;
/// How long a closed connection lingers (fading) before it disappears.
const NET_FADE_SECS: f64 = 6.0;

/// The top-level tools.
#[derive(PartialEq, Eq, Clone, Copy)]
enum Tab {
    Explorer,
    Network,
    Persistence,
    Providers,
}

/// A connection tracked across snapshots so it can fade out after it closes.
struct TrackedConn {
    conn: Connection,
    last_seen: f64,
    /// Present in the most recent snapshot?
    alive: bool,
}

/// What an in-flight request id was asking for — used to clear the correct
/// loading state when a reply (or error) arrives.
enum PendingKind {
    Namespaces(String),
    Classes,
    Query,
    Network,
    Events,
    Providers,
    Schema,
    Mof,
    Instances,
    Invoke,
    Search,
}

/// A dangerous-looking method name gets an extra warning in the confirm modal.
fn is_dangerous_method(method: &str) -> bool {
    let m = method.to_lowercase();
    [
        "create",
        "delete",
        "terminate",
        "reboot",
        "shutdown",
        "format",
        "change",
        "rename",
        "uninstall",
        "setpowerstate",
        "stopservice",
        "kill",
        "write",
        "set",
    ]
    .iter()
    .any(|k| m.contains(k))
}

/// Colour for a subscription risk level.
fn risk_color(risk: Risk) -> Color32 {
    match risk {
        Risk::High => Color32::from_rgb(240, 100, 100),
        Risk::Medium => Color32::from_rgb(225, 185, 90),
        Risk::Low => Color32::from_rgb(150, 165, 150),
    }
}

/// Which view the Explorer central panel shows for the selected class.
#[derive(PartialEq, Eq, Clone, Copy)]
enum CentralView {
    Instances,
    Schema,
}

/// Target language for the script generator.
#[derive(PartialEq, Eq, Clone, Copy)]
enum ScriptLang {
    PowerShell,
    VbScript,
}

/// Produce a runnable script equivalent to the current namespace + WQL query.
fn generate_script(lang: ScriptLang, namespace: &str, wql: &str) -> String {
    let ns = namespace.trim();
    let q = wql.trim();
    match lang {
        ScriptLang::PowerShell => format!(
            "# Generated by VMI-Scope\n\
             $namespace = '{ns}'\n\
             $query     = @'\n\
             {q}\n\
             '@\n\n\
             Get-CimInstance -Namespace $namespace -Query $query | Format-List *\n"
        ),
        ScriptLang::VbScript => {
            let q = q.replace('"', "\"\""); // VBScript escapes quotes by doubling
            format!(
                "' Generated by VMI-Scope\n\
                 strNamespace = \"{ns}\"\n\
                 strQuery     = \"{q}\"\n\n\
                 Set objWMI   = GetObject(\"winmgmts:\\\\.\\\" & strNamespace)\n\
                 Set colItems = objWMI.ExecQuery(strQuery)\n\
                 For Each objItem In colItems\n\
                 \x20   WScript.Echo \"----------------------------------------\"\n\
                 \x20   For Each objProp In objItem.Properties_\n\
                 \x20       WScript.Echo objProp.Name & \" = \" & objProp.Value\n\
                 \x20   Next\n\
                 Next\n"
            )
        }
    }
}

/// Colour a connection by protocol/state (before fade alpha is applied).
fn state_color(state: &str, proto: Protocol) -> Color32 {
    if proto == Protocol::Udp {
        return Color32::from_rgb(120, 170, 220);
    }
    match state {
        "Established" => Color32::from_rgb(120, 210, 140), // green — active
        "Listen" | "Bound" => Color32::from_rgb(120, 170, 220), // blue — server socket
        "SynSent" | "SynReceived" | "FinWait1" | "FinWait2" | "CloseWait" | "Closing"
        | "LastAck" | "TimeWait" => Color32::from_rgb(220, 190, 110), // amber — transitional
        "Closed" | "DeleteTCB" => Color32::from_rgb(165, 165, 165), // gray
        _ => Color32::from_rgb(205, 205, 205),
    }
}

/// The display string for a network table column (kept in sync with the header
/// order so sorting matches what's shown).
fn net_col_value(c: &Connection, col: usize) -> String {
    match col {
        0 => c.proto.as_str().to_string(),
        1 => c.state.clone(),
        2 => c.local_addr.clone(),
        3 => c.local_port.to_string(),
        4 => c.remote_addr.clone(),
        5 => {
            if c.proto == Protocol::Udp {
                String::new()
            } else {
                c.remote_port.to_string()
            }
        }
        6 => c.pid.to_string(),
        7 => c.process.clone(),
        _ => String::new(),
    }
}

/// The display/sort string for a persistence table column. Column 0 (risk) maps
/// to a numeric severity so sorting orders by danger, not alphabetically.
fn sub_col_value(s: &Subscription, col: usize) -> String {
    match col {
        0 => match s.risk {
            Risk::High => "3",
            Risk::Medium => "2",
            Risk::Low => "1",
        }
        .to_string(),
        1 => s.consumer_type.clone(),
        2 => s.consumer_name.clone(),
        3 => s.filter_name.clone(),
        4 => {
            if s.action.is_empty() {
                s.filter_query.clone()
            } else {
                s.action.clone()
            }
        }
        5 => s.reasons.join("; "),
        _ => String::new(),
    }
}

/// The display/sort string for a providers table column.
fn prov_col_value(p: &ProviderInfo, col: usize) -> String {
    match col {
        0 => p.provider.clone(),
        1 => p.namespace.clone(),
        2 => p.host_pid.to_string(),
        3 => p.host_process.clone(),
        4 => p.hosting_group.clone(),
        _ => String::new(),
    }
}

/// Compare two cells numerically when both parse as numbers, else case-insensitively.
fn smart_cmp(a: &str, b: &str) -> std::cmp::Ordering {
    match (a.parse::<f64>(), b.parse::<f64>()) {
        (Ok(x), Ok(y)) => x.partial_cmp(&y).unwrap_or(std::cmp::Ordering::Equal),
        _ => a.to_lowercase().cmp(&b.to_lowercase()),
    }
}

/// Cycle a column's sort: unsorted → ascending → descending → unsorted.
fn toggle_sort(current: &mut Option<(usize, bool)>, col: usize) {
    *current = match *current {
        Some((c, true)) if c == col => Some((col, false)),
        Some((c, false)) if c == col => None,
        _ => Some((col, true)),
    };
}

/// A sortable header cell: shows the title plus a ▲/▼ marker when it's the
/// active sort column. Returns true if the user clicked it.
fn sortable_header(
    ui: &mut egui::Ui,
    title: &str,
    col: usize,
    sort: Option<(usize, bool)>,
) -> bool {
    let marker = match sort {
        Some((c, true)) if c == col => " \u{25b2}",
        Some((c, false)) if c == col => " \u{25bc}",
        _ => "",
    };
    ui.add(egui::Button::new(egui::RichText::new(format!("{title}{marker}")).strong()).frame(false))
        .clicked()
}

pub struct VmiScopeApp {
    worker: WmiWorker,
    next_id: u64,
    pending: HashMap<u64, PendingKind>,
    active_tab: Tab,
    /// Cached class list per namespace (avoids re-enumerating on revisit).
    class_cache: HashMap<String, Vec<String>>,

    // --- network tab ---
    net_conns: HashMap<String, TrackedConn>,
    net_last_refresh: f64,
    net_inflight: bool,
    net_filter: String,
    net_paused: bool,
    /// (column index, ascending). `None` = default (grouped by process).
    net_sort: Option<(usize, bool)>,

    // --- persistence tab ---
    events_report: Option<SubscriptionReport>,
    events_loading: bool,
    events_sort: Option<(usize, bool)>,

    // --- providers tab ---
    providers: Option<Vec<ProviderInfo>>,
    providers_loading: bool,
    providers_sort: Option<(usize, bool)>,

    // --- namespace tree ---
    /// namespace path -> its loaded child paths (absent = not loaded yet).
    ns_children: HashMap<String, Vec<String>>,
    ns_expanded: HashSet<String>,
    ns_loading: HashSet<String>,
    active_ns: String,

    // --- class list (for the active namespace) ---
    classes: Vec<String>,
    classes_ns: String,
    classes_loading: bool,
    class_filter: String,
    selected_class: Option<String>,

    // --- query + results ---
    query_text: String,
    script_lang: ScriptLang,
    central_view: CentralView,
    schema: Option<ClassSchema>,
    schema_class: String,
    schema_loading: bool,
    schema_filter: String,
    // --- MOF viewer (floating window) ---
    mof_open: bool,
    mof_title: String,
    mof_object_path: String,
    mof_text: Option<String>,
    mof_loading: bool,
    // --- Actions (method execution) panel ---
    actions_open: bool,
    act_method: Option<String>,
    act_args: HashMap<String, String>,
    act_bools: HashMap<String, bool>,
    act_target: String,
    act_instances: Option<Vec<MethodTarget>>,
    act_instances_loading: bool,
    act_invoking: bool,
    act_outcome: Option<(String, MethodOutcome)>,
    confirm_open: bool,
    // --- global search ---
    search_index: Option<SearchIndex>,
    search_loading: bool,
    search_text: String,
    search_methods: bool,
    latest_query_id: u64,
    query_loading: bool,
    result: Option<QueryResult>,
    result_wql: String,
    selected_row: Option<usize>,
    /// (column index, ascending). `None` = original result order.
    result_sort: Option<(usize, bool)>,

    // --- status ---
    error: Option<String>,
}

impl VmiScopeApp {
    pub fn new(cc: &eframe::CreationContext<'_>) -> Self {
        cc.egui_ctx.set_visuals(egui::Visuals::dark());

        let mut app = Self {
            worker: WmiWorker::spawn(),
            next_id: 0,
            pending: HashMap::new(),
            active_tab: Tab::Explorer,
            class_cache: HashMap::new(),
            net_conns: HashMap::new(),
            net_last_refresh: 0.0,
            net_inflight: false,
            net_filter: String::new(),
            net_paused: false,
            net_sort: None,
            events_report: None,
            events_loading: false,
            events_sort: None,
            providers: None,
            providers_loading: false,
            providers_sort: None,
            ns_children: HashMap::new(),
            ns_expanded: HashSet::new(),
            ns_loading: HashSet::new(),
            active_ns: DEFAULT_NAMESPACE.to_string(),
            classes: Vec::new(),
            classes_ns: String::new(),
            classes_loading: false,
            class_filter: String::new(),
            selected_class: None,
            query_text: DEFAULT_QUERY.to_string(),
            script_lang: ScriptLang::PowerShell,
            central_view: CentralView::Instances,
            schema: None,
            schema_class: String::new(),
            schema_loading: false,
            schema_filter: String::new(),
            mof_open: false,
            mof_title: String::new(),
            mof_object_path: String::new(),
            mof_text: None,
            mof_loading: false,
            actions_open: false,
            act_method: None,
            act_args: HashMap::new(),
            act_bools: HashMap::new(),
            act_target: String::new(),
            act_instances: None,
            act_instances_loading: false,
            act_invoking: false,
            act_outcome: None,
            confirm_open: false,
            search_index: None,
            search_loading: false,
            search_text: String::new(),
            search_methods: false,
            latest_query_id: 0,
            query_loading: false,
            result: None,
            result_wql: String::new(),
            selected_row: None,
            result_sort: None,
            error: None,
        };

        // Load the root's children, expand it, focus CIMV2, and run a query so
        // the window has real content the moment it opens.
        app.ns_expanded.insert(ROOT_NAMESPACE.to_string());
        app.request_namespaces(ROOT_NAMESPACE.to_string());
        app.request_classes(DEFAULT_NAMESPACE.to_string());
        app.run_query();
        app
    }

    // ------------------------------------------------------------------
    // request helpers
    // ------------------------------------------------------------------

    fn alloc_id(&mut self) -> u64 {
        self.next_id += 1;
        self.next_id
    }

    fn request_namespaces(&mut self, namespace: String) {
        if self.ns_loading.contains(&namespace) || self.ns_children.contains_key(&namespace) {
            return;
        }
        let id = self.alloc_id();
        self.ns_loading.insert(namespace.clone());
        self.pending
            .insert(id, PendingKind::Namespaces(namespace.clone()));
        self.worker
            .send(Request::ListChildNamespaces { id, namespace });
    }

    fn request_classes(&mut self, namespace: String) {
        self.classes_ns = namespace.clone();
        // Serve from cache instantly when we've already enumerated this namespace.
        if let Some(cached) = self.class_cache.get(&namespace) {
            self.classes = cached.clone();
            self.classes_loading = false;
            return;
        }
        let id = self.alloc_id();
        self.classes_loading = true;
        self.classes.clear();
        self.pending.insert(id, PendingKind::Classes);
        self.worker.send(Request::ListClasses { id, namespace });
    }

    fn request_network(&mut self, now: f64) {
        let id = self.alloc_id();
        self.net_inflight = true;
        self.net_last_refresh = now;
        self.pending.insert(id, PendingKind::Network);
        self.worker.send(Request::NetworkSnapshot { id });
    }

    fn request_events(&mut self) {
        let id = self.alloc_id();
        self.events_loading = true;
        self.pending.insert(id, PendingKind::Events);
        self.worker.send(Request::ListEventSubscriptions { id });
    }

    fn request_providers(&mut self) {
        let id = self.alloc_id();
        self.providers_loading = true;
        self.pending.insert(id, PendingKind::Providers);
        self.worker.send(Request::ListProviders { id });
    }

    fn request_schema(&mut self, class: String) {
        if class.is_empty() {
            return;
        }
        // Already have (or are fetching) this class's schema.
        if self.schema_class == class && (self.schema.is_some() || self.schema_loading) {
            return;
        }
        let id = self.alloc_id();
        self.schema_class = class.clone();
        self.schema = None;
        self.schema_loading = true;
        self.pending.insert(id, PendingKind::Schema);
        self.worker.send(Request::ClassSchema {
            id,
            namespace: self.active_ns.clone(),
            class,
        });
    }

    fn request_search_index(&mut self, include_methods: bool) {
        let id = self.alloc_id();
        self.search_loading = true;
        self.pending.insert(id, PendingKind::Search);
        self.worker.send(Request::BuildSearchIndex {
            id,
            namespace: self.active_ns.clone(),
            include_methods,
        });
    }

    fn request_instances(&mut self, class: String) {
        let id = self.alloc_id();
        self.act_instances_loading = true;
        self.pending.insert(id, PendingKind::Instances);
        self.worker.send(Request::ListInstances {
            id,
            namespace: self.active_ns.clone(),
            class,
        });
    }

    fn request_invoke(
        &mut self,
        class: String,
        object_path: String,
        method: String,
        is_static: bool,
        args: Vec<MethodArg>,
    ) {
        let id = self.alloc_id();
        self.act_invoking = true;
        self.act_outcome = None;
        self.pending.insert(id, PendingKind::Invoke);
        self.worker.send(Request::InvokeMethod {
            id,
            namespace: self.active_ns.clone(),
            class,
            object_path,
            method,
            is_static,
            args,
        });
    }

    fn request_mof(&mut self, object_path: String, title: String) {
        let id = self.alloc_id();
        self.mof_open = true;
        self.mof_loading = true;
        self.mof_title = title;
        self.mof_object_path = object_path.clone();
        self.mof_text = None;
        self.pending.insert(id, PendingKind::Mof);
        self.worker.send(Request::ClassMof {
            id,
            namespace: self.active_ns.clone(),
            object_path,
        });
    }

    fn run_query(&mut self) {
        let wql = self.query_text.trim().to_string();
        if wql.is_empty() {
            return;
        }
        let id = self.alloc_id();
        self.latest_query_id = id;
        self.query_loading = true;
        self.error = None;
        self.pending.insert(id, PendingKind::Query);
        self.worker.send(Request::Query {
            id,
            namespace: self.active_ns.clone(),
            wql,
        });
    }

    // ------------------------------------------------------------------
    // selection actions
    // ------------------------------------------------------------------

    fn select_namespace(&mut self, namespace: String) {
        if self.active_ns == namespace {
            return;
        }
        self.active_ns = namespace.clone();
        self.selected_class = None;
        self.schema = None;
        self.schema_class.clear();
        self.request_classes(namespace);
    }

    fn toggle_namespace(&mut self, path: &str) {
        if self.ns_expanded.contains(path) {
            self.ns_expanded.remove(path);
        } else {
            self.ns_expanded.insert(path.to_string());
            self.request_namespaces(path.to_string());
        }
    }

    fn select_class(&mut self, class: String) {
        self.query_text = format!("SELECT * FROM {class}");
        self.selected_class = Some(class.clone());
        self.run_query();
        if self.central_view == CentralView::Schema {
            self.request_schema(class);
        }
    }

    // ------------------------------------------------------------------
    // response handling
    // ------------------------------------------------------------------

    fn handle_responses(&mut self, now: f64) {
        for resp in self.worker.poll() {
            match resp {
                Response::ChildNamespaces {
                    id,
                    namespace,
                    children,
                } => {
                    self.pending.remove(&id);
                    self.ns_loading.remove(&namespace);
                    self.ns_children.insert(namespace, children);
                }
                Response::Classes {
                    id,
                    namespace,
                    classes,
                } => {
                    self.pending.remove(&id);
                    // Only apply if it still matches the namespace we care about.
                    if namespace == self.classes_ns {
                        self.classes = classes.clone();
                        self.classes_loading = false;
                    }
                    self.class_cache.insert(namespace, classes);
                }
                Response::QueryResult {
                    id, wql, result, ..
                } => {
                    self.pending.remove(&id);
                    // Ignore stale results from superseded queries.
                    if id == self.latest_query_id {
                        self.result = Some(result);
                        self.result_wql = wql;
                        self.selected_row = None;
                        self.result_sort = None;
                        self.query_loading = false;
                        self.error = None;
                    }
                }
                Response::Network { id, snapshot } => {
                    self.pending.remove(&id);
                    self.net_inflight = false;
                    // Mark everything stale, then revive whatever is present now.
                    for tc in self.net_conns.values_mut() {
                        tc.alive = false;
                    }
                    for conn in snapshot.connections {
                        let key = conn.key();
                        match self.net_conns.get_mut(&key) {
                            Some(tc) => {
                                tc.conn = conn;
                                tc.last_seen = now;
                                tc.alive = true;
                            }
                            None => {
                                self.net_conns.insert(
                                    key,
                                    TrackedConn {
                                        conn,
                                        last_seen: now,
                                        alive: true,
                                    },
                                );
                            }
                        }
                    }
                    // Drop connections that have fully faded out.
                    self.net_conns
                        .retain(|_, tc| tc.alive || (now - tc.last_seen) < NET_FADE_SECS);
                }
                Response::EventSubscriptions { id, report } => {
                    self.pending.remove(&id);
                    self.events_loading = false;
                    self.events_report = Some(report);
                }
                Response::Providers { id, providers } => {
                    self.pending.remove(&id);
                    self.providers_loading = false;
                    self.providers = Some(providers);
                }
                Response::Schema {
                    id, class, schema, ..
                } => {
                    self.pending.remove(&id);
                    if class == self.schema_class {
                        self.schema = Some(schema);
                        self.schema_loading = false;
                    }
                }
                Response::Mof {
                    id,
                    object_path,
                    mof,
                } => {
                    self.pending.remove(&id);
                    if object_path == self.mof_object_path {
                        self.mof_text = Some(mof);
                        self.mof_loading = false;
                    }
                }
                Response::Instances { id, targets, .. } => {
                    self.pending.remove(&id);
                    self.act_instances_loading = false;
                    self.act_instances = Some(targets);
                }
                Response::MethodDone {
                    id,
                    method,
                    outcome,
                    ..
                } => {
                    self.pending.remove(&id);
                    self.act_invoking = false;
                    self.act_outcome = Some((method, outcome));
                }
                Response::SearchIndex { id, index } => {
                    self.pending.remove(&id);
                    self.search_loading = false;
                    self.search_index = Some(index);
                }
                Response::Error {
                    id,
                    context,
                    message,
                } => {
                    let kind = self.pending.remove(&id);
                    match kind {
                        Some(PendingKind::Namespaces(ns)) => {
                            self.ns_loading.remove(&ns);
                        }
                        Some(PendingKind::Classes) => {
                            self.classes_loading = false;
                        }
                        Some(PendingKind::Query) => {
                            if id == self.latest_query_id {
                                self.query_loading = false;
                            }
                        }
                        Some(PendingKind::Network) => {
                            self.net_inflight = false;
                        }
                        Some(PendingKind::Events) => {
                            self.events_loading = false;
                        }
                        Some(PendingKind::Providers) => {
                            self.providers_loading = false;
                        }
                        Some(PendingKind::Schema) => {
                            self.schema_loading = false;
                        }
                        Some(PendingKind::Mof) => {
                            self.mof_loading = false;
                        }
                        Some(PendingKind::Instances) => {
                            self.act_instances_loading = false;
                        }
                        Some(PendingKind::Invoke) => {
                            self.act_invoking = false;
                        }
                        Some(PendingKind::Search) => {
                            self.search_loading = false;
                        }
                        None => {}
                    }
                    self.error = Some(format!("{context}\n{message}"));
                }
            }
        }
    }

    // ------------------------------------------------------------------
    // UI: namespace tree
    // ------------------------------------------------------------------

    fn ui_namespace_tree(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            ui.strong("Namespaces");
            if self.ns_loading.contains(ROOT_NAMESPACE) {
                ui.spinner();
            }
        });
        ui.separator();
        egui::ScrollArea::vertical()
            .id_salt("ns-tree")
            .max_height(ui.available_height() * 0.45)
            .auto_shrink([false, false])
            .show(ui, |ui| {
                self.ui_namespace_node(ui, ROOT_NAMESPACE.to_string(), 0);
            });
    }

    fn ui_namespace_node(&mut self, ui: &mut egui::Ui, path: String, depth: usize) {
        let expanded = self.ns_expanded.contains(&path);
        let leaf = path.rsplit('\\').next().unwrap_or(&path).to_string();

        ui.horizontal(|ui| {
            ui.add_space(depth as f32 * 14.0);
            let arrow = if expanded { "\u{25be}" } else { "\u{25b8}" }; // ▾ / ▸
            if ui
                .add(egui::Button::new(arrow).frame(false))
                .on_hover_text("Expand / collapse")
                .clicked()
            {
                self.toggle_namespace(&path);
            }
            if ui
                .selectable_label(self.active_ns.eq_ignore_ascii_case(&path), &leaf)
                .clicked()
            {
                self.select_namespace(path.clone());
            }
        });

        if expanded {
            match self.ns_children.get(&path).cloned() {
                Some(children) => {
                    for child in children {
                        self.ui_namespace_node(ui, child, depth + 1);
                    }
                }
                None => {
                    ui.horizontal(|ui| {
                        ui.add_space((depth as f32 + 1.0) * 14.0);
                        ui.spinner();
                        ui.weak("loading\u{2026}");
                    });
                }
            }
        }
    }

    // ------------------------------------------------------------------
    // UI: class list
    // ------------------------------------------------------------------

    fn ui_class_list(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            ui.strong("Classes");
            if self.classes_loading {
                ui.spinner();
            }
            ui.weak(format!("({})", self.classes.len()));
        });
        ui.horizontal(|ui| {
            ui.label("\u{1f50d}");
            ui.add(
                egui::TextEdit::singleline(&mut self.class_filter)
                    .hint_text("filter classes")
                    .desired_width(f32::INFINITY),
            );
        });
        ui.separator();

        let mut clicked: Option<String> = None;
        {
            let filter = self.class_filter.to_lowercase();
            let filtered: Vec<&String> = self
                .classes
                .iter()
                .filter(|c| filter.is_empty() || c.to_lowercase().contains(&filter))
                .collect();
            let row_h = ui.text_style_height(&egui::TextStyle::Body) + 4.0;
            egui::ScrollArea::vertical()
                .id_salt("class-list")
                .auto_shrink([false, false])
                .show_rows(ui, row_h, filtered.len(), |ui, range| {
                    for i in range {
                        let class = filtered[i];
                        let selected = self.selected_class.as_deref() == Some(class.as_str());
                        if ui.selectable_label(selected, class).clicked() {
                            clicked = Some(class.clone());
                        }
                    }
                });
        }
        if let Some(class) = clicked {
            self.select_class(class);
        }
    }

    // ------------------------------------------------------------------
    // UI: query editor + results table
    // ------------------------------------------------------------------

    fn ui_central(&mut self, ui: &mut egui::Ui) {
        // View switch for the selected class.
        let prev_view = self.central_view;
        let mut mof_click: Option<String> = None;
        let mut open_actions_for: Option<String> = None;
        ui.horizontal(|ui| {
            ui.selectable_value(
                &mut self.central_view,
                CentralView::Instances,
                "\u{1f4c4} Instances",
            );
            ui.selectable_value(
                &mut self.central_view,
                CentralView::Schema,
                "\u{1f9ec} Schema",
            );
            if let Some(c) = self.selected_class.clone() {
                ui.separator();
                ui.weak(&c);
                if ui
                    .button("\u{1f4c4} MOF")
                    .on_hover_text("Show MOF text")
                    .clicked()
                {
                    mof_click = Some(c.clone());
                }
                let was_open = self.actions_open;
                if ui
                    .selectable_label(self.actions_open, "\u{2699} Actions")
                    .on_hover_text("Invoke methods (mutating)")
                    .clicked()
                {
                    self.actions_open = !self.actions_open;
                }
                if self.actions_open && !was_open {
                    open_actions_for = Some(c);
                }
            }
        });
        if let Some(c) = mof_click {
            self.request_mof(c.clone(), c);
        }
        if let Some(c) = open_actions_for {
            self.act_method = None;
            self.act_outcome = None;
            self.act_instances = None;
            self.request_schema(c);
        }
        // Fetch schema the moment the user flips to the Schema view.
        if self.central_view == CentralView::Schema && prev_view != CentralView::Schema {
            if let Some(c) = self.selected_class.clone() {
                self.request_schema(c);
            }
        }
        ui.separator();

        if self.central_view == CentralView::Schema {
            self.ui_schema(ui);
            return;
        }

        // Query bar.
        ui.horizontal(|ui| {
            ui.strong("WQL");
            ui.weak(&self.active_ns);
            if self.query_loading {
                ui.spinner();
            }
        });
        let run_shortcut = ui.input(|i| i.modifiers.command && i.key_pressed(egui::Key::Enter));
        ui.add(
            egui::TextEdit::multiline(&mut self.query_text)
                .desired_rows(2)
                .desired_width(f32::INFINITY)
                .code_editor()
                .hint_text("SELECT * FROM Win32_Process"),
        );
        ui.horizontal(|ui| {
            if ui.button("\u{25b6} Run  (Ctrl+Enter)").clicked() || run_shortcut {
                self.run_query();
            }
            if let Some(result) = &self.result {
                ui.weak(format!(
                    "{} rows \u{00d7} {} cols",
                    result.rows.len(),
                    result.columns.len()
                ));
            }
        });

        self.ui_script_gen(ui);
        ui.separator();

        // Results table (virtualized, sortable by clicking a header).
        let selected_row = self.selected_row;
        let sort = self.result_sort;
        let mut newly_clicked: Option<usize> = None;
        let mut header_clicked: Option<usize> = None;
        if let Some(result) = self.result.as_ref() {
            if result.columns.is_empty() {
                ui.weak("Query returned no columns.");
            } else {
                // Row display order for the active sort column.
                let mut order: Vec<usize> = (0..result.rows.len()).collect();
                if let Some((ci, asc)) = sort {
                    order.sort_by(|&a, &b| {
                        let av = result.rows[a].get(ci).map(String::as_str).unwrap_or("");
                        let bv = result.rows[b].get(ci).map(String::as_str).unwrap_or("");
                        let o = smart_cmp(av, bv);
                        if asc {
                            o
                        } else {
                            o.reverse()
                        }
                    });
                }

                let row_h = ui.text_style_height(&egui::TextStyle::Body) + 6.0;
                let ncols = result.columns.len();
                let mut table = TableBuilder::new(ui)
                    .id_salt("results-table")
                    .striped(true)
                    .resizable(true)
                    .sense(egui::Sense::click())
                    .cell_layout(egui::Layout::left_to_right(egui::Align::Center))
                    .min_scrolled_height(0.0);
                for _ in 0..ncols {
                    table = table.column(
                        Column::initial(150.0)
                            .at_least(48.0)
                            .clip(true)
                            .resizable(true),
                    );
                }
                table
                    .header(22.0, |mut header| {
                        for (ci, col) in result.columns.iter().enumerate() {
                            header.col(|ui| {
                                if sortable_header(ui, col, ci, sort) {
                                    header_clicked = Some(ci);
                                }
                            });
                        }
                    })
                    .body(|body| {
                        body.rows(row_h, order.len(), |mut row| {
                            let actual = order[row.index()];
                            row.set_selected(selected_row == Some(actual));
                            for cell in &result.rows[actual] {
                                row.col(|ui| {
                                    ui.label(cell);
                                });
                            }
                            if row.response().clicked() {
                                newly_clicked = Some(actual);
                            }
                        });
                    });
            }
        } else {
            ui.weak("Run a query to see results.");
        }
        if let Some(ci) = header_clicked {
            toggle_sort(&mut self.result_sort, ci);
        }
        if let Some(ri) = newly_clicked {
            self.selected_row = Some(ri);
        }
    }

    /// Collapsible PowerShell / VBScript generator for the current query.
    fn ui_script_gen(&mut self, ui: &mut egui::Ui) {
        ui.collapsing("\u{1f4dc} Generate script (PowerShell / VBScript)", |ui| {
            ui.horizontal(|ui| {
                ui.selectable_value(&mut self.script_lang, ScriptLang::PowerShell, "PowerShell");
                ui.selectable_value(&mut self.script_lang, ScriptLang::VbScript, "VBScript");
            });
            let script = generate_script(self.script_lang, &self.active_ns, &self.query_text);
            ui.horizontal(|ui| {
                if ui.button("\u{1f4cb} Copy").clicked() {
                    ui.ctx().copy_text(script.clone());
                }
                ui.weak("PowerShell: paste & run \u{00b7} VBScript: cscript file.vbs");
            });
            egui::ScrollArea::vertical()
                .id_salt("script-box")
                .max_height(150.0)
                .auto_shrink([false, false])
                .show(ui, |ui| {
                    ui.add(
                        egui::Label::new(egui::RichText::new(script.as_str()).monospace())
                            .selectable(true),
                    );
                });
        });
    }

    // ------------------------------------------------------------------
    // UI: reflective class schema
    // ------------------------------------------------------------------

    fn ui_schema(&mut self, ui: &mut egui::Ui) {
        if self.selected_class.is_none() {
            ui.weak("Select a class to view its schema.");
            return;
        }
        if self.schema.is_none() {
            if self.schema_loading {
                ui.horizontal(|ui| {
                    ui.spinner();
                    ui.weak("reflecting schema\u{2026}");
                });
            } else {
                ui.weak("No schema available for this class.");
            }
            return;
        }

        // Header (scoped immutable borrow so the filter box can borrow mutably next).
        {
            let s = self.schema.as_ref().unwrap();
            ui.horizontal(|ui| {
                ui.heading(s.class.as_str());
                if s.is_abstract {
                    ui.weak("[abstract]");
                }
                if let Some(sup) = &s.super_class {
                    ui.weak(format!(": {sup}"));
                }
                ui.weak(format!(
                    "\u{00b7} {} props \u{00b7} {} methods",
                    s.properties.len(),
                    s.methods.len()
                ));
            });
            if let Some(d) = &s.description {
                ui.label(d);
            }
        }
        ui.horizontal(|ui| {
            ui.label("\u{1f50d}");
            ui.add(
                egui::TextEdit::singleline(&mut self.schema_filter)
                    .hint_text("filter properties / methods")
                    .desired_width(240.0),
            );
        });
        ui.separator();

        let filter = self.schema_filter.to_lowercase();
        let schema = self.schema.as_ref().unwrap();
        egui::ScrollArea::vertical()
            .auto_shrink([false, false])
            .show(ui, |ui| {
                ui.strong("Properties");
                egui::Grid::new("schema-props")
                    .num_columns(4)
                    .striped(true)
                    .spacing([14.0, 3.0])
                    .show(ui, |ui| {
                        ui.strong("Name");
                        ui.strong("Type");
                        ui.strong("Flags");
                        ui.strong("Description");
                        ui.end_row();
                        for p in schema.properties.iter().filter(|p| {
                            filter.is_empty()
                                || p.name.to_lowercase().contains(&filter)
                                || p.cim_type.to_lowercase().contains(&filter)
                        }) {
                            let label = if p.is_key {
                                format!("\u{1f511} {}", p.name)
                            } else {
                                p.name.clone()
                            };
                            let resp = ui.label(label);
                            if !p.value_map.is_empty() {
                                let vm = p
                                    .value_map
                                    .iter()
                                    .map(|(c, l)| format!("{c} = {l}"))
                                    .collect::<Vec<_>>()
                                    .join("\n");
                                resp.on_hover_text(format!("ValueMap:\n{vm}"));
                            }
                            ui.label(p.cim_type.as_str());
                            let flags = format!(
                                "{}{}{}",
                                if p.is_read { "R" } else { "" },
                                if p.is_write { "W" } else { "" },
                                if p.is_key { "K" } else { "" }
                            );
                            ui.label(flags);
                            ui.label(
                                p.units
                                    .as_deref()
                                    .map(|u| format!("[{u}] "))
                                    .unwrap_or_default()
                                    + p.description.as_deref().unwrap_or_default(),
                            );
                            ui.end_row();
                        }
                    });

                ui.add_space(10.0);
                ui.strong("Methods");
                let methods: Vec<_> = schema
                    .methods
                    .iter()
                    .filter(|m| filter.is_empty() || m.name.to_lowercase().contains(&filter))
                    .collect();
                if methods.is_empty() {
                    ui.weak("(none)");
                }
                for m in methods {
                    let tag = if m.is_static { "  [static]" } else { "" };
                    egui::CollapsingHeader::new(format!("{}(){tag}", m.name))
                        .id_salt(m.name.as_str())
                        .show(ui, |ui| {
                            if let Some(d) = &m.description {
                                ui.label(d);
                            }
                            if !m.in_params.is_empty() {
                                ui.weak("in:");
                                for p in &m.in_params {
                                    let opt = if p.optional { "  (optional)" } else { "" };
                                    ui.label(format!("    {} : {}{opt}", p.name, p.cim_type));
                                }
                            }
                            if !m.out_params.is_empty() {
                                ui.weak("out:");
                                for p in &m.out_params {
                                    ui.label(format!("    {} : {}", p.name, p.cim_type));
                                }
                            }
                        });
                }
            });
    }

    // ------------------------------------------------------------------
    // UI: MOF viewer (floating window)
    // ------------------------------------------------------------------

    fn ui_mof_window(&mut self, ctx: &egui::Context) {
        if !self.mof_open {
            return;
        }
        let mut open = self.mof_open;
        egui::Window::new(format!("MOF \u{2014} {}", self.mof_title))
            .open(&mut open)
            .default_size([560.0, 460.0])
            .show(ctx, |ui| {
                if self.mof_loading {
                    ui.horizontal(|ui| {
                        ui.spinner();
                        ui.weak("loading MOF\u{2026}");
                    });
                }
                if let Some(text) = self.mof_text.clone() {
                    if ui.button("\u{1f4cb} Copy").clicked() {
                        ui.ctx().copy_text(text.clone());
                    }
                    egui::ScrollArea::both()
                        .auto_shrink([false, false])
                        .show(ui, |ui| {
                            ui.add(
                                egui::Label::new(egui::RichText::new(text.as_str()).monospace())
                                    .selectable(true),
                            );
                        });
                }
            });
        self.mof_open = open;
    }

    // ------------------------------------------------------------------
    // UI: Actions (method execution)
    // ------------------------------------------------------------------

    fn ui_actions(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            ui.strong("\u{2699} Actions");
            if self.act_invoking {
                ui.spinner();
            }
        });
        ui.weak("invoke WMI methods \u{2014} may change system state");
        ui.separator();

        let Some(class) = self.selected_class.clone() else {
            ui.weak("Select a class first.");
            return;
        };

        // Method signatures come from the reflected schema.
        if self.schema_class != class || self.schema.is_none() {
            ui.horizontal(|ui| {
                ui.spinner();
                ui.weak("loading class methods\u{2026}");
            });
            return;
        }

        // Owned method metadata so the schema borrow is released for the widgets.
        struct MInfo {
            name: String,
            is_static: bool,
            inputs: Vec<(String, String)>,
        }
        let methods: Vec<MInfo> = self
            .schema
            .as_ref()
            .unwrap()
            .methods
            .iter()
            .map(|m| MInfo {
                name: m.name.clone(),
                is_static: m.is_static,
                inputs: m
                    .in_params
                    .iter()
                    .map(|p| (p.name.clone(), p.cim_type.clone()))
                    .collect(),
            })
            .collect();
        if methods.is_empty() {
            ui.weak("This class has no methods.");
            return;
        }

        // Method picker.
        let current = self.act_method.clone().unwrap_or_default();
        egui::ComboBox::from_id_salt("act-method")
            .width(f32::INFINITY)
            .selected_text(if current.is_empty() {
                "\u{2014} pick a method \u{2014}".to_string()
            } else {
                current.clone()
            })
            .show_ui(ui, |ui| {
                for m in &methods {
                    let tag = if m.is_static { "  [static]" } else { "" };
                    if ui
                        .selectable_label(
                            self.act_method.as_deref() == Some(m.name.as_str()),
                            format!("{}{tag}", m.name),
                        )
                        .clicked()
                    {
                        self.act_method = Some(m.name.clone());
                        self.act_args.clear();
                        self.act_bools.clear();
                        self.act_outcome = None;
                    }
                }
            });

        let Some(mname) = self.act_method.clone() else {
            return;
        };
        let Some(minfo) = methods.iter().find(|m| m.name == mname) else {
            return;
        };
        ui.separator();

        // Target (non-static methods need an instance).
        if minfo.is_static {
            ui.weak("target: static (class-level)");
        } else {
            ui.horizontal(|ui| {
                ui.label("target:");
                if ui.button("Load instances").clicked() {
                    self.request_instances(class.clone());
                }
                if self.act_instances_loading {
                    ui.spinner();
                }
            });
            if let Some(insts) = self.act_instances.clone() {
                let sel = self.act_target.clone();
                let text = if sel.is_empty() {
                    "\u{2014} pick instance \u{2014}".to_string()
                } else {
                    insts
                        .iter()
                        .find(|t| t.path == sel)
                        .map(|t| t.label.clone())
                        .unwrap_or(sel)
                };
                egui::ComboBox::from_id_salt("act-target")
                    .width(f32::INFINITY)
                    .selected_text(text)
                    .show_ui(ui, |ui| {
                        for t in &insts {
                            if ui
                                .selectable_label(self.act_target == t.path, &t.label)
                                .clicked()
                            {
                                self.act_target = t.path.clone();
                            }
                        }
                    });
            }
            ui.add(
                egui::TextEdit::singleline(&mut self.act_target)
                    .hint_text("or paste an object path")
                    .desired_width(f32::INFINITY),
            );
        }

        // Inputs.
        if !minfo.inputs.is_empty() {
            ui.separator();
            ui.weak("inputs:");
        }
        for (pname, ctype) in &minfo.inputs {
            let kind = param_kind(ctype);
            match kind {
                ParamKind::Bool => {
                    let b = self.act_bools.entry(pname.clone()).or_insert(false);
                    ui.checkbox(b, format!("{pname}  ({ctype})"));
                }
                ParamKind::Other => {
                    ui.weak(format!("{pname} ({ctype}) \u{2014} unsupported"));
                }
                _ => {
                    ui.label(format!("{pname}  ({ctype})"));
                    let v = self.act_args.entry(pname.clone()).or_default();
                    ui.add(egui::TextEdit::singleline(v).desired_width(f32::INFINITY));
                }
            }
        }

        ui.separator();
        let can_invoke =
            !self.act_invoking && (minfo.is_static || !self.act_target.trim().is_empty());
        ui.add_enabled_ui(can_invoke, |ui| {
            let btn = egui::Button::new(
                egui::RichText::new(format!("\u{26a0} Invoke {class}.{mname}"))
                    .color(Color32::WHITE),
            )
            .fill(Color32::from_rgb(150, 60, 60));
            if ui.add(btn).clicked() {
                self.confirm_open = true;
            }
        });

        // Result.
        if let Some((m, outcome)) = self.act_outcome.clone() {
            ui.separator();
            ui.strong(format!("Result of {m}"));
            if let Some(rv) = &outcome.return_value {
                let color = if rv == "0" {
                    Color32::from_rgb(120, 210, 140)
                } else {
                    Color32::from_rgb(230, 180, 90)
                };
                ui.colored_label(color, format!("ReturnValue = {rv}"));
            }
            egui::ScrollArea::vertical()
                .max_height(200.0)
                .auto_shrink([false, false])
                .show(ui, |ui| {
                    egui::Grid::new("act-out")
                        .num_columns(2)
                        .striped(true)
                        .show(ui, |ui| {
                            for (k, v) in &outcome.outputs {
                                ui.strong(k);
                                let short: String = v.chars().take(200).collect();
                                ui.label(short);
                                ui.end_row();
                            }
                        });
                });
        }
    }

    fn ui_confirm_window(&mut self, ctx: &egui::Context) {
        if !self.confirm_open {
            return;
        }
        let class = self.selected_class.clone().unwrap_or_default();
        let method = self.act_method.clone().unwrap_or_default();
        if class.is_empty() || method.is_empty() {
            self.confirm_open = false;
            return;
        }

        // Reconstruct the argument list from the current inputs + schema signature.
        let (is_static, inputs): (bool, Vec<(String, String)>) = self
            .schema
            .as_ref()
            .and_then(|s| s.methods.iter().find(|m| m.name == method))
            .map(|m| {
                (
                    m.is_static,
                    m.in_params
                        .iter()
                        .map(|p| (p.name.clone(), p.cim_type.clone()))
                        .collect(),
                )
            })
            .unwrap_or((true, Vec::new()));
        let target = self.act_target.clone();
        let ns = self.active_ns.clone();
        let mut args: Vec<MethodArg> = Vec::new();
        for (pname, ctype) in &inputs {
            let kind = param_kind(ctype);
            let value = match kind {
                ParamKind::Bool => self
                    .act_bools
                    .get(pname)
                    .copied()
                    .unwrap_or(false)
                    .to_string(),
                _ => self.act_args.get(pname).cloned().unwrap_or_default(),
            };
            args.push(MethodArg {
                name: pname.clone(),
                kind,
                value,
            });
        }

        let mut open = true;
        let mut do_invoke = false;
        let mut cancel = false;
        egui::Window::new("Confirm invocation")
            .collapsible(false)
            .resizable(false)
            .open(&mut open)
            .show(ctx, |ui| {
                ui.colored_label(
                    Color32::from_rgb(240, 120, 120),
                    "\u{26a0} This invokes a WMI method and may change system state.",
                );
                if is_dangerous_method(&method) {
                    ui.colored_label(
                        Color32::from_rgb(255, 80, 80),
                        format!("\u{201c}{method}\u{201d} looks destructive \u{2014} double-check the target."),
                    );
                }
                ui.separator();
                egui::Grid::new("confirm-grid").num_columns(2).show(ui, |ui| {
                    ui.strong("Namespace");
                    ui.label(&ns);
                    ui.end_row();
                    ui.strong("Class");
                    ui.label(&class);
                    ui.end_row();
                    ui.strong("Method");
                    ui.label(&method);
                    ui.end_row();
                    ui.strong("Target");
                    ui.label(if is_static {
                        "(static)"
                    } else if target.is_empty() {
                        "(none)"
                    } else {
                        target.as_str()
                    });
                    ui.end_row();
                });
                if !args.is_empty() {
                    ui.separator();
                    ui.strong("Arguments");
                    for a in &args {
                        let shown = if a.value.trim().is_empty() {
                            "(provider default)".to_string()
                        } else {
                            a.value.clone()
                        };
                        ui.label(format!("  {} = {shown}", a.name));
                    }
                }
                ui.separator();
                ui.horizontal(|ui| {
                    if ui.button("Cancel").clicked() {
                        cancel = true;
                    }
                    let go = egui::Button::new(
                        egui::RichText::new("Yes, invoke").color(Color32::WHITE),
                    )
                    .fill(Color32::from_rgb(150, 60, 60));
                    if ui.add(go).clicked() {
                        do_invoke = true;
                    }
                });
            });

        if cancel || !open {
            self.confirm_open = false;
        }
        if do_invoke {
            self.confirm_open = false;
            self.request_invoke(class, target, method, is_static, args);
        }
    }

    // ------------------------------------------------------------------
    // UI: selected-row detail
    // ------------------------------------------------------------------

    fn ui_detail(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            ui.strong("Row detail");
            if ui.small_button("\u{2715}").on_hover_text("Close").clicked() {
                self.selected_row = None;
            }
        });
        ui.separator();
        let (Some(result), Some(ri)) = (self.result.as_ref(), self.selected_row) else {
            return;
        };
        let Some(row) = result.rows.get(ri) else {
            return;
        };
        egui::ScrollArea::vertical()
            .auto_shrink([false, false])
            .show(ui, |ui| {
                egui::Grid::new("detail-grid")
                    .num_columns(2)
                    .striped(true)
                    .spacing([12.0, 4.0])
                    .show(ui, |ui| {
                        for (col, val) in result.columns.iter().zip(row.iter()) {
                            ui.strong(col);
                            if val.is_empty() {
                                ui.weak("\u{2014}"); // em dash for empty
                            } else {
                                ui.label(val);
                            }
                            ui.end_row();
                        }
                    });
            });
    }

    // ------------------------------------------------------------------
    // UI: live network monitor
    // ------------------------------------------------------------------

    fn ui_network(&mut self, ui: &mut egui::Ui, now: f64) {
        // Controls.
        ui.horizontal(|ui| {
            ui.strong("Live connections");
            if self.net_inflight {
                ui.spinner();
            }
            let pause = if self.net_paused {
                "\u{25b6} Resume"
            } else {
                "\u{23f8} Pause"
            };
            if ui.button(pause).clicked() {
                self.net_paused = !self.net_paused;
            }
            if ui.button("\u{21bb} Refresh").clicked() {
                self.request_network(now);
            }
            ui.separator();
            ui.label("\u{1f50d}");
            ui.add(
                egui::TextEdit::singleline(&mut self.net_filter)
                    .hint_text("filter process / ip / port / state")
                    .desired_width(240.0),
            );
        });

        let active = self.net_conns.values().filter(|t| t.alive).count();
        let fading = self.net_conns.len().saturating_sub(active);
        ui.horizontal(|ui| {
            ui.colored_label(
                Color32::from_rgb(120, 210, 140),
                format!("\u{25cf} {active} active"),
            );
            ui.weak(format!("\u{25cb} {fading} closing"));
            ui.weak("\u{2014}  auto-refresh 1.5s, closed connections fade out over ~6s");
        });
        ui.separator();

        // Filter + sort (stable order so fading rows stay put while they dim).
        let filter = self.net_filter.to_lowercase();
        let mut rows: Vec<&TrackedConn> = self
            .net_conns
            .values()
            .filter(|t| {
                if filter.is_empty() {
                    return true;
                }
                let c = &t.conn;
                c.process.to_lowercase().contains(&filter)
                    || c.local_addr.contains(&filter)
                    || c.remote_addr.contains(&filter)
                    || c.local_port.to_string().contains(&filter)
                    || c.remote_port.to_string().contains(&filter)
                    || c.state.to_lowercase().contains(&filter)
            })
            .collect();
        let sort = self.net_sort;
        match sort {
            Some((ci, asc)) => rows.sort_by(|a, b| {
                let o = smart_cmp(&net_col_value(&a.conn, ci), &net_col_value(&b.conn, ci));
                if asc {
                    o
                } else {
                    o.reverse()
                }
            }),
            // Default: group by process, then local port (stable while fading).
            None => rows.sort_by(|a, b| {
                a.conn
                    .process
                    .to_lowercase()
                    .cmp(&b.conn.process.to_lowercase())
                    .then(a.conn.proto.as_str().cmp(b.conn.proto.as_str()))
                    .then(a.conn.local_port.cmp(&b.conn.local_port))
                    .then(a.conn.remote_addr.cmp(&b.conn.remote_addr))
                    .then(a.conn.remote_port.cmp(&b.conn.remote_port))
            }),
        }

        let headers = [
            "Proto",
            "State",
            "Local address",
            "L.Port",
            "Remote address",
            "R.Port",
            "PID",
            "Process",
        ];
        let widths = [52.0, 96.0, 190.0, 60.0, 190.0, 60.0, 64.0, 180.0];
        let row_h = ui.text_style_height(&egui::TextStyle::Body) + 6.0;

        let mut header_clicked: Option<usize> = None;
        let mut table = TableBuilder::new(ui)
            .id_salt("net-table")
            .striped(true)
            .resizable(true)
            .cell_layout(egui::Layout::left_to_right(egui::Align::Center))
            .min_scrolled_height(0.0);
        for w in widths {
            table = table.column(Column::initial(w).at_least(40.0).clip(true).resizable(true));
        }
        table
            .header(22.0, |mut header| {
                for (ci, h) in headers.iter().enumerate() {
                    header.col(|ui| {
                        if sortable_header(ui, h, ci, sort) {
                            header_clicked = Some(ci);
                        }
                    });
                }
            })
            .body(|body| {
                body.rows(row_h, rows.len(), |mut row| {
                    let t = rows[row.index()];
                    let c = &t.conn;
                    // Alpha: full while alive, fading toward transparent after close.
                    let alpha = if t.alive {
                        1.0
                    } else {
                        (1.0 - (now - t.last_seen) / NET_FADE_SECS).clamp(0.06, 1.0) as f32
                    };
                    let color = state_color(&c.state, c.proto).gamma_multiply(alpha);

                    let is_udp = c.proto == Protocol::Udp;
                    let cells = [
                        c.proto.as_str().to_string(),
                        if c.state.is_empty() {
                            "\u{2014}".into()
                        } else {
                            c.state.clone()
                        },
                        c.local_addr.clone(),
                        c.local_port.to_string(),
                        if c.remote_addr.is_empty() {
                            "*".into()
                        } else {
                            c.remote_addr.clone()
                        },
                        if is_udp {
                            "*".into()
                        } else {
                            c.remote_port.to_string()
                        },
                        c.pid.to_string(),
                        c.process.clone(),
                    ];
                    for cell in cells {
                        row.col(|ui| {
                            ui.label(egui::RichText::new(cell).color(color));
                        });
                    }
                });
            });

        if let Some(ci) = header_clicked {
            toggle_sort(&mut self.net_sort, ci);
        }
    }

    // ------------------------------------------------------------------
    // UI: persistence (WMI event-subscription hunter)
    // ------------------------------------------------------------------

    fn ui_persistence(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            ui.strong("WMI event subscriptions");
            if self.events_loading {
                ui.spinner();
            }
            if ui.button("\u{21bb} Refresh").clicked() {
                self.request_events();
            }
            ui.weak("root\\subscription — permanent subscriptions (persistence)");
        });

        if let Some(report) = self.events_report.as_ref() {
            ui.horizontal(|ui| {
                ui.colored_label(
                    risk_color(Risk::High),
                    format!("\u{25cf} {} high", report.count(Risk::High)),
                );
                ui.colored_label(
                    risk_color(Risk::Medium),
                    format!("\u{25cf} {} medium", report.count(Risk::Medium)),
                );
                ui.colored_label(
                    risk_color(Risk::Low),
                    format!("\u{25cf} {} low", report.count(Risk::Low)),
                );
            });
        }
        ui.separator();

        let sort = self.events_sort;
        let mut header_clicked: Option<usize> = None;

        if let Some(report) = self.events_report.as_ref() {
            if report.subscriptions.is_empty() {
                ui.weak("No permanent event subscriptions found.");
            } else {
                let mut order: Vec<usize> = (0..report.subscriptions.len()).collect();
                if let Some((ci, asc)) = sort {
                    order.sort_by(|&a, &b| {
                        let o = smart_cmp(
                            &sub_col_value(&report.subscriptions[a], ci),
                            &sub_col_value(&report.subscriptions[b], ci),
                        );
                        if asc {
                            o
                        } else {
                            o.reverse()
                        }
                    });
                }

                let headers = [
                    "Risk",
                    "Consumer type",
                    "Consumer",
                    "Filter",
                    "Action / query",
                    "Why",
                ];
                let widths = [64.0, 168.0, 150.0, 150.0, 260.0, 220.0];
                let row_h = ui.text_style_height(&egui::TextStyle::Body) + 6.0;

                let mut table = TableBuilder::new(ui)
                    .id_salt("events-table")
                    .striped(true)
                    .resizable(true)
                    .cell_layout(egui::Layout::left_to_right(egui::Align::Center))
                    .min_scrolled_height(0.0);
                for w in widths {
                    table =
                        table.column(Column::initial(w).at_least(48.0).clip(true).resizable(true));
                }
                table
                    .header(22.0, |mut header| {
                        for (ci, h) in headers.iter().enumerate() {
                            header.col(|ui| {
                                if sortable_header(ui, h, ci, sort) {
                                    header_clicked = Some(ci);
                                }
                            });
                        }
                    })
                    .body(|body| {
                        body.rows(row_h, order.len(), |mut row| {
                            let s = &report.subscriptions[order[row.index()]];
                            let color = risk_color(s.risk);
                            row.col(|ui| {
                                ui.label(
                                    egui::RichText::new(s.risk.as_str()).color(color).strong(),
                                );
                            });
                            row.col(|ui| {
                                ui.label(s.consumer_type.as_str());
                            });
                            row.col(|ui| {
                                ui.label(s.consumer_name.as_str());
                            });
                            row.col(|ui| {
                                ui.label(s.filter_name.as_str());
                            });
                            row.col(|ui| {
                                let text = if s.action.is_empty() {
                                    s.filter_query.as_str()
                                } else {
                                    s.action.as_str()
                                };
                                ui.label(text).on_hover_text(format!(
                                    "filter query:\n{}\n\naction:\n{}",
                                    s.filter_query, s.action
                                ));
                            });
                            row.col(|ui| {
                                let why = s.reasons.join("; ");
                                ui.label(egui::RichText::new(why.as_str()).color(color))
                                    .on_hover_text(why);
                            });
                        });
                    });
            }
        } else if !self.events_loading {
            ui.weak("Click Refresh to scan for WMI persistence.");
        }

        if let Some(ci) = header_clicked {
            toggle_sort(&mut self.events_sort, ci);
        }
    }

    // ------------------------------------------------------------------
    // UI: WMI providers → host processes
    // ------------------------------------------------------------------

    fn ui_providers(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            ui.strong("WMI providers");
            if self.providers_loading {
                ui.spinner();
            }
            if ui.button("\u{21bb} Refresh").clicked() {
                self.request_providers();
            }
            if let Some(p) = self.providers.as_ref() {
                ui.weak(format!("({})", p.len()));
            }
            ui.weak("Msft_Providers — which process hosts each provider");
        });
        ui.separator();

        let sort = self.providers_sort;
        let mut header_clicked: Option<usize> = None;

        if let Some(providers) = self.providers.as_ref() {
            if providers.is_empty() {
                ui.weak("No providers returned.");
            } else {
                let mut order: Vec<usize> = (0..providers.len()).collect();
                if let Some((ci, asc)) = sort {
                    order.sort_by(|&a, &b| {
                        let o = smart_cmp(
                            &prov_col_value(&providers[a], ci),
                            &prov_col_value(&providers[b], ci),
                        );
                        if asc {
                            o
                        } else {
                            o.reverse()
                        }
                    });
                }

                let headers = [
                    "Provider",
                    "Namespace",
                    "Host PID",
                    "Host process",
                    "Hosting group",
                ];
                let widths = [220.0, 160.0, 74.0, 170.0, 200.0];
                let row_h = ui.text_style_height(&egui::TextStyle::Body) + 6.0;

                let mut table = TableBuilder::new(ui)
                    .id_salt("providers-table")
                    .striped(true)
                    .resizable(true)
                    .cell_layout(egui::Layout::left_to_right(egui::Align::Center))
                    .min_scrolled_height(0.0);
                for w in widths {
                    table =
                        table.column(Column::initial(w).at_least(48.0).clip(true).resizable(true));
                }
                table
                    .header(22.0, |mut header| {
                        for (ci, h) in headers.iter().enumerate() {
                            header.col(|ui| {
                                if sortable_header(ui, h, ci, sort) {
                                    header_clicked = Some(ci);
                                }
                            });
                        }
                    })
                    .body(|body| {
                        body.rows(row_h, order.len(), |mut row| {
                            let p = &providers[order[row.index()]];
                            row.col(|ui| {
                                ui.label(p.provider.as_str());
                            });
                            row.col(|ui| {
                                ui.label(p.namespace.as_str());
                            });
                            row.col(|ui| {
                                ui.label(p.host_pid.to_string());
                            });
                            row.col(|ui| {
                                ui.label(p.host_process.as_str());
                            });
                            row.col(|ui| {
                                ui.label(p.hosting_group.as_str());
                            });
                        });
                    });
            }
        } else if !self.providers_loading {
            ui.weak("Click Refresh to list WMI providers.");
        }

        if let Some(ci) = header_clicked {
            toggle_sort(&mut self.providers_sort, ci);
        }
    }

    // ------------------------------------------------------------------
    // Global search
    // ------------------------------------------------------------------

    fn compute_hits(&self, q: &str) -> Vec<SearchHit> {
        let Some(idx) = self.search_index.as_ref() else {
            return Vec::new();
        };
        let mut hits = Vec::new();
        for c in &idx.classes {
            if c.to_lowercase().contains(q) {
                hits.push(SearchHit {
                    class: c.clone(),
                    member: None,
                    is_method: false,
                });
            }
        }
        for (class, props) in &idx.properties {
            for p in props {
                if p.to_lowercase().contains(q) {
                    hits.push(SearchHit {
                        class: class.clone(),
                        member: Some(p.clone()),
                        is_method: false,
                    });
                }
            }
        }
        if idx.has_methods {
            for (class, methods) in &idx.methods {
                for m in methods {
                    if m.to_lowercase().contains(q) {
                        hits.push(SearchHit {
                            class: class.clone(),
                            member: Some(m.clone()),
                            is_method: true,
                        });
                    }
                }
            }
        }
        // Stable order (HashMap iteration is not deterministic).
        hits.sort_by(|a, b| {
            a.class
                .to_lowercase()
                .cmp(&b.class.to_lowercase())
                .then(a.member.cmp(&b.member))
        });
        hits.truncate(300);
        hits
    }

    fn apply_search_hit(&mut self, h: SearchHit) {
        self.central_view = CentralView::Instances;
        match h.member {
            None => self.select_class(h.class),
            Some(m) if h.is_method => {
                self.selected_class = Some(h.class.clone());
                self.query_text = format!("SELECT * FROM {}", h.class);
                self.run_query();
                self.actions_open = true;
                self.act_method = Some(m);
                self.act_args.clear();
                self.act_bools.clear();
                self.act_outcome = None;
                self.request_schema(h.class);
            }
            Some(m) => {
                self.selected_class = Some(h.class.clone());
                self.query_text = format!("SELECT {m} FROM {}", h.class);
                self.run_query();
            }
        }
    }

    fn ui_search(&mut self, ui: &mut egui::Ui) {
        egui::CollapsingHeader::new("\u{1f50d} Global search")
            .id_salt("global-search")
            .show(ui, |ui| {
                let mut build = false;
                ui.horizontal(|ui| {
                    if ui.button("Build index").clicked() {
                        build = true;
                    }
                    ui.checkbox(&mut self.search_methods, "methods");
                    if self.search_loading {
                        ui.spinner();
                    }
                });
                if build {
                    self.request_search_index(self.search_methods);
                }
                let indexed = self.search_index.as_ref().map(|i| i.classes.len());
                match indexed {
                    None => {
                        ui.weak("build the index to search class / property / method names");
                        return;
                    }
                    Some(n) => {
                        ui.weak(format!("{n} classes indexed"));
                    }
                }
                ui.add(
                    egui::TextEdit::singleline(&mut self.search_text)
                        .hint_text("search names")
                        .desired_width(f32::INFINITY),
                );
                let q = self.search_text.trim().to_lowercase();
                if q.len() < 2 {
                    ui.weak("type at least 2 characters");
                    return;
                }
                let hits = self.compute_hits(&q);
                let mut clicked: Option<SearchHit> = None;
                egui::ScrollArea::vertical()
                    .id_salt("search-results")
                    .max_height(240.0)
                    .auto_shrink([false, false])
                    .show(ui, |ui| {
                        if hits.is_empty() {
                            ui.weak("no matches");
                        }
                        for h in &hits {
                            let label = match &h.member {
                                None => format!("\u{1f5c2} {}", h.class),
                                Some(m) if h.is_method => format!("{} :: {}()", h.class, m),
                                Some(m) => format!("{} :: {}", h.class, m),
                            };
                            if ui.selectable_label(false, label).clicked() {
                                clicked = Some(h.clone());
                            }
                        }
                    });
                if let Some(h) = clicked {
                    self.apply_search_hit(h);
                }
            });
    }

    // ------------------------------------------------------------------
    // UI: status bar
    // ------------------------------------------------------------------

    fn ui_status(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            if let Some(err) = &self.error {
                ui.colored_label(egui::Color32::from_rgb(240, 90, 90), "\u{26a0} error");
                ui.weak("\u{2014}");
                ui.label(err.replace('\n', "  \u{2014}  "));
            } else {
                ui.weak(format!("Namespace: {}", self.active_ns));
                if !self.result_wql.is_empty() {
                    ui.weak("\u{2014}");
                    ui.weak(&self.result_wql);
                }
            }
        });
    }
}

impl eframe::App for VmiScopeApp {
    // eframe 0.35 hands the app the root `Ui` directly and attaches panels to it
    // via `show(ui, ..)` (instead of the older `update(ctx, ..)` model).
    fn ui(&mut self, ui: &mut egui::Ui, _frame: &mut eframe::Frame) {
        let now = ui.input(|i| i.time);
        self.handle_responses(now);

        // Drive the live network refresh from the frame clock.
        if self.active_tab == Tab::Network
            && !self.net_paused
            && !self.net_inflight
            && (now - self.net_last_refresh) >= NET_REFRESH_SECS
        {
            self.request_network(now);
        }

        // Load the persistence scan the first time its tab is opened.
        if self.active_tab == Tab::Persistence
            && self.events_report.is_none()
            && !self.events_loading
        {
            self.request_events();
        }

        // Load the provider list the first time its tab is opened.
        if self.active_tab == Tab::Providers && self.providers.is_none() && !self.providers_loading
        {
            self.request_providers();
        }

        egui::Panel::top("top").show(ui, |ui| {
            ui.add_space(4.0);
            ui.horizontal(|ui| {
                ui.heading("VMI-Scope");
                ui.separator();
                ui.selectable_value(&mut self.active_tab, Tab::Explorer, "\u{1f5c2} Explorer");
                ui.selectable_value(&mut self.active_tab, Tab::Network, "\u{1f5a7} Network");
                ui.selectable_value(
                    &mut self.active_tab,
                    Tab::Persistence,
                    "\u{1f6e1} Persistence",
                );
                ui.selectable_value(&mut self.active_tab, Tab::Providers, "\u{1f9e9} Providers");
            });
            ui.add_space(4.0);
        });

        egui::Panel::bottom("status").show(ui, |ui| {
            self.ui_status(ui);
        });

        match self.active_tab {
            Tab::Explorer => {
                egui::Panel::left("browser")
                    .resizable(true)
                    .default_size(300.0)
                    .size_range(egui::Rangef::new(200.0, 520.0))
                    .show(ui, |ui| {
                        self.ui_namespace_tree(ui);
                        ui.add_space(6.0);
                        self.ui_search(ui);
                        ui.add_space(6.0);
                        self.ui_class_list(ui);
                    });

                if self.actions_open {
                    egui::Panel::right("actions")
                        .resizable(true)
                        .default_size(360.0)
                        .size_range(egui::Rangef::new(260.0, 620.0))
                        .show(ui, |ui| {
                            self.ui_actions(ui);
                        });
                }

                if self.selected_row.is_some() {
                    egui::Panel::right("detail")
                        .resizable(true)
                        .default_size(340.0)
                        .size_range(egui::Rangef::new(220.0, 560.0))
                        .show(ui, |ui| {
                            self.ui_detail(ui);
                        });
                }

                egui::CentralPanel::default().show(ui, |ui| {
                    self.ui_central(ui);
                });
            }
            Tab::Network => {
                egui::CentralPanel::default().show(ui, |ui| {
                    self.ui_network(ui, now);
                });
            }
            Tab::Persistence => {
                egui::CentralPanel::default().show(ui, |ui| {
                    self.ui_persistence(ui);
                });
            }
            Tab::Providers => {
                egui::CentralPanel::default().show(ui, |ui| {
                    self.ui_providers(ui);
                });
            }
        }

        // MOF viewer and the method-invocation confirmation float above the tabs.
        self.ui_mof_window(ui.ctx());
        self.ui_confirm_window(ui.ctx());

        // Repaint while work is in flight, and continuously on the live tab.
        if !self.pending.is_empty() {
            ui.ctx().request_repaint_after(Duration::from_millis(30));
        }
        if self.active_tab == Tab::Network && !self.net_paused {
            ui.ctx().request_repaint_after(Duration::from_millis(200));
        }
    }
}
