//! Module-scope helpers shared by the views: sort comparators, table column
//! accessors, script generation, and the native save dialog.

use crate::app::ScriptLang;

use vmiscope_core::{Connection, Protocol, ProviderInfo, Risk, Subscription};

/// A dangerous-looking method name gets an extra warning in the confirm modal.
pub(crate) fn is_dangerous_method(method: &str) -> bool {
    let m = method.to_lowercase();
    [
        "create",
        "delete",
        "terminate",
        "reboot",
        "shutdown",
        "format",
        "change",
        "rename",
        "uninstall",
        "setpowerstate",
        "stopservice",
        "kill",
        "write",
        "set",
    ]
    .iter()
    .any(|k| m.contains(k))
}

/// Open a native "Save as" dialog and write `contents` to the chosen path.
pub(crate) fn save_file(default_name: &str, contents: &str) {
    if let Some(path) = rfd::FileDialog::new()
        .set_file_name(default_name)
        .save_file()
    {
        let _ = std::fs::write(path, contents);
    }
}

/// Produce a runnable script equivalent to the current namespace + WQL query.
pub(crate) fn generate_script(lang: ScriptLang, namespace: &str, wql: &str) -> String {
    let ns = namespace.trim();
    let q = wql.trim();
    match lang {
        ScriptLang::PowerShell => format!(
            "# Generated by VMI-Scope\n\
             $namespace = '{ns}'\n\
             $query     = @'\n\
             {q}\n\
             '@\n\n\
             Get-CimInstance -Namespace $namespace -Query $query | Format-List *\n"
        ),
        ScriptLang::VbScript => {
            let q = q.replace('"', "\"\""); // VBScript escapes quotes by doubling
            format!(
                "' Generated by VMI-Scope\n\
                 strNamespace = \"{ns}\"\n\
                 strQuery     = \"{q}\"\n\n\
                 Set objWMI   = GetObject(\"winmgmts:\\\\.\\\" & strNamespace)\n\
                 Set colItems = objWMI.ExecQuery(strQuery)\n\
                 For Each objItem In colItems\n\
                 \x20   WScript.Echo \"----------------------------------------\"\n\
                 \x20   For Each objProp In objItem.Properties_\n\
                 \x20       WScript.Echo objProp.Name & \" = \" & objProp.Value\n\
                 \x20   Next\n\
                 Next\n"
            )
        }
    }
}

/// The display string for a network table column (kept in sync with the header
/// order so sorting matches what's shown).
pub(crate) fn net_col_value(c: &Connection, col: usize) -> String {
    match col {
        0 => c.proto.as_str().to_string(),
        1 => c.state.clone(),
        2 => c.local_addr.clone(),
        3 => c.local_port.to_string(),
        4 => c.remote_addr.clone(),
        5 => {
            if c.proto == Protocol::Udp {
                String::new()
            } else {
                c.remote_port.to_string()
            }
        }
        6 => c.pid.to_string(),
        7 => c.process.clone(),
        _ => String::new(),
    }
}

/// The display/sort string for a persistence table column. Column 0 (risk) maps
/// to a numeric severity so sorting orders by danger, not alphabetically.
pub(crate) fn sub_col_value(s: &Subscription, col: usize) -> String {
    match col {
        0 => match s.risk {
            Risk::High => "3",
            Risk::Medium => "2",
            Risk::Low => "1",
        }
        .to_string(),
        1 => s.consumer_type.clone(),
        2 => s.consumer_name.clone(),
        3 => s.filter_name.clone(),
        4 => {
            if s.action.is_empty() {
                s.filter_query.clone()
            } else {
                s.action.clone()
            }
        }
        5 => s.reasons.join("; "),
        _ => String::new(),
    }
}

/// The display/sort string for a providers table column.
pub(crate) fn prov_col_value(p: &ProviderInfo, col: usize) -> String {
    match col {
        0 => p.provider.clone(),
        1 => p.namespace.clone(),
        2 => p.host_pid.to_string(),
        3 => p.host_process.clone(),
        4 => p.hosting_group.clone(),
        _ => String::new(),
    }
}

/// Compare two cells numerically when both parse as numbers, else case-insensitively.
pub(crate) fn smart_cmp(a: &str, b: &str) -> std::cmp::Ordering {
    match (a.parse::<f64>(), b.parse::<f64>()) {
        (Ok(x), Ok(y)) => x.partial_cmp(&y).unwrap_or(std::cmp::Ordering::Equal),
        _ => a.to_lowercase().cmp(&b.to_lowercase()),
    }
}

// `toggle_sort` lived here until the Explorer's results grid -- the last
// hand-rolled `TableBuilder` -- moved onto `DataTable`, which owns the
// tri-state cycle itself as `widgets::table::cycle_sort`.
