//! Turning a namespace + WQL query into a runnable script in one of four host
//! languages.
//!
//! This is the canonical generator. It lives in core (not the GUI) because the
//! translation is pure text with no egui in it, and because the same four arms
//! back both the Explorer's Code sub-tab and any future export path. The GUI's
//! two-way language selector (`config::CodeLang`) maps onto the two arms it
//! persists; the C# and WQL arms exist here so a caller that wants all four does
//! not have to reach into a view module for them.

/// The target language for [`generate_script`].
///
/// PowerShell and VBScript emit a small program that runs the query and prints
/// each property; C# emits the `System.Management` equivalent; WQL hands the
/// query back, since it is already the target language.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ScriptLang {
    PowerShell,
    CSharp,
    VbScript,
    Wql,
}

/// Produce a runnable script equivalent to `SELECT ... FROM <class>` in
/// `namespace`, in the requested language.
///
/// `namespace` and `wql` are trimmed. Languages that embed the query in a string
/// literal escape it for that literal's rules (VBScript and C# both double a
/// `"`); the WQL arm performs no translation at all.
pub fn generate_script(lang: ScriptLang, namespace: &str, wql: &str) -> String {
    let ns = namespace.trim();
    let q = wql.trim();
    match lang {
        ScriptLang::PowerShell => powershell(ns, q),
        ScriptLang::CSharp => csharp(ns, q),
        ScriptLang::VbScript => vbscript(ns, q),
        ScriptLang::Wql => wql_passthrough(q),
    }
}

fn powershell(ns: &str, q: &str) -> String {
    // The query goes in a here-string (`@' … '@`) so a multi-line WQL survives
    // and nothing inside it needs escaping.
    format!(
        "# Generated by VMI-Scope\n\
         $namespace = '{ns}'\n\
         $query     = @'\n\
         {q}\n\
         '@\n\n\
         Get-CimInstance -Namespace $namespace -Query $query | Format-List *\n"
    )
}

fn vbscript(ns: &str, q: &str) -> String {
    // VBScript string literals escape a quote by doubling it.
    let q = q.replace('"', "\"\"");
    format!(
        "' Generated by VMI-Scope\n\
         strNamespace = \"{ns}\"\n\
         strQuery     = \"{q}\"\n\n\
         Set objWMI   = GetObject(\"winmgmts:\\\\.\\\" & strNamespace)\n\
         Set colItems = objWMI.ExecQuery(strQuery)\n\
         For Each objItem In colItems\n\
         \x20   WScript.Echo \"----------------------------------------\"\n\
         \x20   For Each objProp In objItem.Properties_\n\
         \x20       WScript.Echo objProp.Name & \" = \" & objProp.Value\n\
         \x20   Next\n\
         Next\n"
    )
}

fn csharp(ns: &str, q: &str) -> String {
    // Both embedded strings are C# verbatim (`@"..."`), so the namespace path's
    // backslashes stay literal and only a `"` in the WQL needs escaping (doubled,
    // per verbatim-string rules).
    let q = q.replace('"', "\"\"");
    format!(
        "// Generated by VMI-Scope\n\
         using System;\n\
         using System.Management;\n\
         \n\
         class Program\n\
         {{\n\
         \x20   static void Main()\n\
         \x20   {{\n\
         \x20       var scope = new ManagementScope(@\"\\\\.\\{ns}\");\n\
         \x20       var query = new ObjectQuery(@\"{q}\");\n\
         \x20       using var searcher = new ManagementObjectSearcher(scope, query);\n\
         \x20       foreach (ManagementObject obj in searcher.Get())\n\
         \x20       {{\n\
         \x20           Console.WriteLine(\"----\");\n\
         \x20           foreach (PropertyData prop in obj.Properties)\n\
         \x20               Console.WriteLine($\"{{prop.Name}} = {{prop.Value}}\");\n\
         \x20       }}\n\
         \x20   }}\n\
         }}\n"
    )
}

fn wql_passthrough(q: &str) -> String {
    // WQL is already the target language, so this hands it back rather than
    // translating it. An empty query would produce an empty file, which is not a
    // runnable statement, so a meta-class enumeration stands in.
    if q.is_empty() {
        "SELECT * FROM meta_class\n".to_string()
    } else {
        format!("{q}\n")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const NS: &str = "root\\CIMV2";
    const Q: &str = "SELECT * FROM Win32_Process";

    /// Every language produces output that names the class it was asked about --
    /// the four-language acceptance for the Code sub-tab.
    #[test]
    fn every_language_carries_the_class() {
        for lang in [
            ScriptLang::PowerShell,
            ScriptLang::CSharp,
            ScriptLang::VbScript,
            ScriptLang::Wql,
        ] {
            let out = generate_script(lang, NS, Q);
            assert!(
                out.contains("Win32_Process"),
                "{lang:?} dropped the class: {out}"
            );
        }
    }

    #[test]
    fn powershell_uses_get_ciminstance() {
        let out = generate_script(ScriptLang::PowerShell, NS, Q);
        assert!(out.contains("Get-CimInstance"), "{out}");
        assert!(out.contains("$namespace = 'root\\CIMV2'"), "{out}");
    }

    #[test]
    fn vbscript_uses_getobject_and_doubles_quotes() {
        let out = generate_script(
            ScriptLang::VbScript,
            NS,
            "SELECT * FROM Win32_Service WHERE Name=\"spooler\"",
        );
        assert!(out.contains("GetObject"), "{out}");
        // The quoted literal is doubled for the VBScript string.
        assert!(out.contains("Name=\"\"spooler\"\""), "{out}");
    }

    /// The C# arm must compile as written: it uses `System.Management`, the
    /// namespace path is a verbatim string so its backslashes survive, and a
    /// quote in the WQL is doubled for the verbatim literal. The brace count is
    /// also balanced, since a stray `{`/`}` from the `format!` escaping would not
    /// compile.
    #[test]
    fn csharp_is_wellformed_system_management() {
        let out = generate_script(
            ScriptLang::CSharp,
            NS,
            "SELECT * FROM Win32_Service WHERE Name=\"spooler\"",
        );
        assert!(out.contains("using System.Management;"), "{out}");
        assert!(out.contains("ManagementObjectSearcher"), "{out}");
        // Verbatim namespace path keeps its backslashes.
        assert!(out.contains("@\"\\\\.\\root\\CIMV2\""), "{out}");
        // Verbatim WQL literal doubles the embedded quote.
        assert!(out.contains("Name=\"\"spooler\"\""), "{out}");
        // The `$"..."` interpolation braces are emitted literally, not consumed
        // by `format!`.
        assert!(out.contains("$\"{prop.Name} = {prop.Value}\""), "{out}");
        assert_eq!(
            out.matches('{').count(),
            out.matches('}').count(),
            "unbalanced braces would not compile: {out}"
        );
    }

    /// WQL is handed back verbatim (plus a trailing newline), and an empty query
    /// falls back to a runnable statement rather than an empty file.
    #[test]
    fn wql_is_passthrough_with_empty_fallback() {
        assert_eq!(generate_script(ScriptLang::Wql, NS, Q).trim(), Q);
        assert_eq!(
            generate_script(ScriptLang::Wql, NS, "   ").trim(),
            "SELECT * FROM meta_class"
        );
    }
}
