//! The Code sub-tab: generate a runnable equivalent of `SELECT * FROM <class>`
//! in PowerShell, C#, VBScript or WQL.

use eframe::egui;

use crate::app::{ScriptLang, VmiScopeApp};
use crate::theme::icons;
use crate::util::{generate_script, save_file};
use crate::views::explorer::CodeTab;
use crate::widgets::button::{btn_secondary, segmented};
use crate::widgets::codeview::{code_panel, Lang};

impl VmiScopeApp {
    pub(crate) fn ui_code_tab(&mut self, ui: &mut egui::Ui) {
        let mut tab = self.code_tab;
        segmented(
            ui,
            &mut tab,
            &[
                (CodeTab::PowerShell, "PowerShell"),
                (CodeTab::CSharp, "C#"),
                (CodeTab::VbScript, "VBScript"),
                (CodeTab::Wql, "WQL"),
            ],
        );
        self.code_tab = tab;

        let ns = self.active_ns.clone();
        // The class's own query, falling back to the live one.
        let wql = match &self.selected_class {
            Some(class) => format!("SELECT * FROM {class}"),
            None => self.query_text.trim().to_string(),
        };

        // Settings -> Code generation -> Include credentials block (task 7.3).
        // WQL is the one tab it cannot reach: a WQL file is a query, and a query
        // has no connection to authenticate.
        let creds = self.config.include_credentials;

        // PowerShell and VBScript go through `util::generate_script`, keeping the
        // two-way `script_lang` (which Settings persists) in step with the tab;
        // C# and WQL are generated here.
        let (code, lang, filename) = match tab {
            CodeTab::PowerShell => {
                self.script_lang = ScriptLang::PowerShell;
                (
                    generate_script(self.script_lang, &ns, &wql, creds),
                    Lang::PowerShell,
                    "query.ps1",
                )
            }
            CodeTab::VbScript => {
                self.script_lang = ScriptLang::VbScript;
                (
                    generate_script(self.script_lang, &ns, &wql, creds),
                    Lang::VbScript,
                    "query.vbs",
                )
            }
            CodeTab::CSharp => (generate_csharp(&ns, &wql, creds), Lang::CSharp, "Query.cs"),
            CodeTab::Wql => (generate_wql(&wql), Lang::Wql, "query.wql"),
        };

        ui.horizontal(|ui| {
            if btn_secondary(ui, icons::labelled(ui, icons::COPY, "Copy")).clicked() {
                ui.ctx().copy_text(code.clone());
            }
            if btn_secondary(
                ui,
                icons::labelled(ui, icons::FLOPPY_DISK, "Save as script"),
            )
            .clicked()
            {
                save_file(filename, &code);
            }
        });
        // The guide is the Settings-level `line_width`; see
        // `widgets::codeview::column_guide` for why it is a guide.
        code_panel(ui, &code, lang, Some(self.config.line_width));
    }
}

/// A C# (`System.Management`) equivalent of the query.
///
/// Both embedded strings are C# verbatim (`@"..."`), so the namespace path's
/// backslashes stay literal and only a `"` in the WQL needs escaping (doubled,
/// per verbatim rules).
/// `credentials` swaps the bare scope for one built from `ConnectionOptions`,
/// which is the only way `System.Management` takes a user and password. As with
/// the other two languages this replaces the *bind*, not a comment above it.
fn generate_csharp(namespace: &str, wql: &str, credentials: bool) -> String {
    let ns = namespace.trim();
    let q = wql.trim().replace('"', "\"\"");
    let scope = if credentials {
        // `SecurePassword` would be the correct field for a real tool; a
        // generated sample that prompts is the honest middle, and a plaintext
        // literal is what this deliberately does not emit.
        format!(
            "\x20       // Alternate credentials (Settings -> Code generation).\n\
             \x20       var options = new ConnectionOptions\n\
             \x20       {{\n\
             \x20           Username = @\"DOMAIN\\user\",\n\
             \x20           Password = ReadPassword(),   // never hard-code one\n\
             \x20           Impersonation = ImpersonationLevel.Impersonate,\n\
             \x20       }};\n\
             \x20       var scope = new ManagementScope(@\"\\\\.\\{ns}\", options);\n\
             \x20       scope.Connect();\n"
        )
    } else {
        format!("\x20       var scope = new ManagementScope(@\"\\\\.\\{ns}\");\n")
    };
    format!(
        "// Generated by VMI-Scope\n\
         using System;\n\
         using System.Management;\n\
         \n\
         class Program\n\
         {{\n\
         \x20   static void Main()\n\
         \x20   {{\n\
         {scope}\
         \x20       var query = new ObjectQuery(@\"{q}\");\n\
         \x20       using var searcher = new ManagementObjectSearcher(scope, query);\n\
         \x20       foreach (ManagementObject obj in searcher.Get())\n\
         \x20       {{\n\
         \x20           Console.WriteLine(\"----\");\n\
         \x20           foreach (PropertyData prop in obj.Properties)\n\
         \x20               Console.WriteLine($\"{{prop.Name}} = {{prop.Value}}\");\n\
         \x20       }}\n\
         \x20   }}\n\
         }}\n"
    )
}

/// The WQL "generation" is the query itself -- it is already the target
/// language, so this hands it back rather than translating it.
fn generate_wql(wql: &str) -> String {
    let q = wql.trim();
    if q.is_empty() {
        "SELECT * FROM meta_class\n".to_string()
    } else {
        format!("{q}\n")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// All four languages produce something, and each carries the class it was
    /// asked about -- the acceptance for task 3.29.
    #[test]
    fn every_language_generates_for_a_class() {
        let ns = "root\\CIMV2";
        let wql = "SELECT * FROM Win32_Process";

        let ps = generate_script(ScriptLang::PowerShell, ns, wql, false);
        assert!(ps.contains("Get-CimInstance") && ps.contains("Win32_Process"));

        let vbs = generate_script(ScriptLang::VbScript, ns, wql, false);
        assert!(vbs.contains("GetObject") && vbs.contains("Win32_Process"));

        let cs = generate_csharp(ns, wql, false);
        assert!(cs.contains("ManagementObjectSearcher"), "{cs}");
        assert!(cs.contains("Win32_Process"));
        // The namespace path is a verbatim string, so its backslash survives.
        assert!(cs.contains("@\"\\\\.\\root\\CIMV2\""), "{cs}");

        let wql_out = generate_wql(wql);
        assert_eq!(wql_out.trim(), wql);
    }

    /// The C# credentials block has to reach the scope the searcher uses, or it
    /// is a comment that compiles.
    #[test]
    fn the_csharp_credentials_block_reaches_the_scope() {
        let cs = generate_csharp("root\\CIMV2", "SELECT * FROM Win32_Process", true);
        assert!(cs.contains("ConnectionOptions"), "{cs}");
        assert!(
            cs.contains("new ManagementScope(@\"\\\\.\\root\\CIMV2\", options)"),
            "the options are not on the scope:\n{cs}"
        );
        assert!(
            cs.contains("new ManagementObjectSearcher(scope, query)"),
            "the searcher no longer uses that scope:\n{cs}"
        );
        // A generated sample must never ship a password literal.
        assert!(!cs.contains("Password = \""), "{cs}");
    }

    /// A `"` in the WQL is doubled for the C# verbatim string, so a WHERE clause
    /// with a string literal still compiles as written.
    #[test]
    fn csharp_escapes_quotes_for_a_verbatim_string() {
        let cs = generate_csharp(
            "root\\CIMV2",
            "SELECT * FROM Win32_Service WHERE Name=\"spooler\"",
            false,
        );
        assert!(cs.contains("Name=\"\"spooler\"\""), "{cs}");
    }
}
